// Generated by designlang v7.0.0
// Source: https://clerk.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF6C47FF);
  static const Color actionSecondary = Color(0xFF1CC4FF);
  static const Color surfaceDefault = Color(0xFFF7F7F8);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 46;
  static const double spacingS2 = 56;
  static const double spacingS3 = 76;
  static const double spacingS4 = 94;
  static const double spacingS5 = 128;
  static const double spacingS6 = 140;
  static const double spacingS7 = 151;
  static const double spacingS8 = 158;
  static const double spacingS9 = 167;
  static const double spacingS10 = 172;
  static const double spacingS11 = 192;
  static const double spacingS12 = 220;
  static const double spacingS13 = 259;
  static const double spacingS14 = 272;
  static const double spacingS15 = 302;
  static const double spacingS16 = 320;
  static const double radiusR0 = 2;
  static const double radiusR1 = 5;
  static const double radiusR2 = 8;
  static const double radiusR3 = 12;
  static const double radiusR4 = 16;
  static const double radiusR5 = 38;
  static const double radiusR6 = 44;
  static const double radiusR7 = 50;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF6C47FF);
  static const Color brandSecondary = Color(0xFF1CC4FF);
  static const Color neutralN100 = Color(0xFFD9D9DE);
  static const Color neutralN200 = Color(0xFF000000);
  static const Color neutralN300 = Color(0xFFFFFFFF);
  static const Color neutralN400 = Color(0xFF131316);
  static const Color neutralN500 = Color(0xFF747686);
  static const Color neutralN600 = Color(0xFF5E5F6E);
  static const Color neutralN700 = Color(0xFF2F3037);
  static const Color neutralN800 = Color(0xFF9394A1);
  static const Color neutralN900 = Color(0xFF696A78);
  static const Color neutralN1000 = Color(0xFFEEEEF0);
  static const Color neutralN1100 = Color(0xFF212126);
  static const Color neutralN1200 = Color(0xFF42434D);
  static const Color neutralN1300 = Color(0xFFB7B8C2);
  static const Color neutralN1400 = Color(0xFF4A4C5B);
  static const Color backgroundBg0 = Color(0xFFF7F7F8);
  static const Color backgroundBg1 = Color(0xFFF8F8F8);
  static const Color backgroundBg2 = Color(0xFF131316);
  static const Color backgroundBg3 = Color(0xFFFFFFFF);
  static const Color backgroundBg4 = Color(0xFF212126);
  static const Color backgroundBg5 = Color(0xFF2D2E3D);
  static const Color backgroundBg6 = Color(0xFF29292E);
  static const Color backgroundBg7 = Color(0xFF25252A);
  static const Color backgroundBg8 = Color(0xFF2F3037);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFFFFFFFF);
  static const Color textText2 = Color(0xFF131316);
  static const Color textText3 = Color(0xFF747686);
  static const Color textText4 = Color(0xFF5E5F6E);
  static const Color textText5 = Color(0xFF212126);
  static const Color textText6 = Color(0xFF6C47FF);
  static const Color textText7 = Color(0xFF9394A1);
  static const Color textText8 = Color(0xFF696A78);
  static const Color textText9 = Color(0xFF42434D);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
