// Generated by designlang v7.0.0
// Source: https://postman.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFE05320)
    val ActionSecondary = Color(0xFF007BFF)
    val SurfaceDefault = Color(0xFFFFFFFF)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFE05320)
    val BrandSecondary = Color(0xFF007BFF)
    val NeutralN100 = Color(0xFF212121)
    val NeutralN200 = Color(0xFF000000)
    val NeutralN300 = Color(0xFF707070)
    val NeutralN400 = Color(0xFFFFFFFF)
    val NeutralN500 = Color(0xFF5C5C5C)
    val NeutralN600 = Color(0xFFE6E6E6)
    val NeutralN700 = Color(0xFF09070D)
    val NeutralN800 = Color(0xFF8A8A8A)
    val NeutralN900 = Color(0xFFCFCFCF)
    val BackgroundBg0 = Color(0xFFFFFFFF)
    val BackgroundBg1 = Color(0xFFF9F8F7)
    val BackgroundBg2 = Color(0xFFFF6C37)
    val BackgroundBg3 = Color(0xFF140B1E)
    val BackgroundBg4 = Color(0xFF09070D)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF212121)
    val TextText2 = Color(0xFF0265D2)
    val TextText3 = Color(0xFF6B6B6B)
    val TextText4 = Color(0xFFE05320)
    val TextText5 = Color(0xFF5C5C5C)
    val TextText6 = Color(0xFFFFFFFF)
    val TextText7 = Color(0xFF707070)
    val TextText8 = Color(0xFF007BFF)
    val SpacingS0 = 1.dp
    val SpacingS1 = 20.dp
    val SpacingS2 = 24.dp
    val SpacingS3 = 40.dp
    val SpacingS4 = 50.dp
    val SpacingS5 = 60.dp
    val SpacingS6 = 64.dp
    val SpacingS7 = 80.dp
    val SpacingS8 = 120.dp
    val SpacingS9 = 224.dp
    val SpacingS10 = 252.dp
    val RadiusR0 = 3.dp
    val RadiusR1 = 10.dp
    val RadiusR2 = 15.dp
    val RadiusR3 = 20.dp
    val RadiusR4 = 9999.dp
}
