// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://supabase.com
// Generated: 2026-06-25T08:25:31.987Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#dfdfdf' | '#171717' | '#525252' | '#707070' | '#ffffff' | '#b2b2b2' | '#000000' | '#c7c7c7' | '#ededed' | '#d4d4d4' | '#3fcf8e' | '#72e3ad' | '#02772d' | '#292929' | '#a9f1ca' | '#00bb68';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Circular' | 'Source Code Pro';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500';

export type SpacingToken = '1px' | '40px' | '48px' | '64px' | '90px' | '112px' | '128px' | '157px' | '208px' | '246px' | '304px';

export type RadiusToken = '6px' | '11px' | '16px';

export type DurationToken = '75ms' | '150ms' | '200ms' | '300ms' | '750ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
