// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://clerk.com
// Generated: 2026-06-25T08:26:24.061Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#d9d9de' | '#000000' | '#ffffff' | '#131316' | '#747686' | '#5e5f6e' | '#2f3037' | '#9394a1' | '#696a78' | '#eeeef0' | '#212126' | '#42434d' | '#b7b8c2' | '#ef4444' | '#6c47ff' | '#1cc4ff' | '#5de3ff' | '#9785ff' | '#4a4c5b' | '#0ba8fa' | '#3ad4fd';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'geistNumbers' | 'soehneMono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600' | '450';

export type SpacingToken = '1px' | '46px' | '56px' | '76px' | '94px' | '128px' | '140px' | '151px' | '158px' | '167px' | '172px' | '192px' | '220px' | '259px' | '272px' | '302px' | '320px';

export type RadiusToken = '2px' | '5px' | '8px' | '12px' | '16px' | '38px' | '44px' | '50px';

export type DurationToken = '150ms' | '200ms' | '300ms' | '450ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
