// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://mintlify.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xFAF8F5)
  static let actionSecondary = Color(hex: 0x004CFF)
  static let surfaceDefault = Color(hex: 0xF9F6F3)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 4
  static let spacingS1: CGFloat = 40
  static let spacingS2: CGFloat = 48
  static let spacingS3: CGFloat = 64
  static let spacingS4: CGFloat = 80
  static let spacingS5: CGFloat = 93
  static let spacingS6: CGFloat = 104
  static let spacingS7: CGFloat = 128
  static let spacingS8: CGFloat = 160
  static let spacingS9: CGFloat = 266
  static let spacingS10: CGFloat = 290
  static let spacingS11: CGFloat = 298

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 6
  static let radiusR2: CGFloat = 12
  static let radiusR3: CGFloat = 24
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xFAF8F5)
  static let brandSecondary = Color(hex: 0x004CFF)
  static let neutralN100 = Color(hex: 0x000000)
  static let neutralN200 = Color(hex: 0xFFFFFF)
  static let neutralN300 = Color(hex: 0x121715)
  static let neutralN400 = Color(hex: 0x969E9B)
  static let neutralN500 = Color(hex: 0x485450)
  static let neutralN600 = Color(hex: 0x717D79)
  static let neutralN700 = Color(hex: 0xCFCDCA)
  static let backgroundBg0 = Color(hex: 0xF9F6F3)
  static let backgroundBg1 = Color(hex: 0xEF6333)
  static let backgroundBg2 = Color(hex: 0x004CFF)
  static let backgroundBg3 = Color(hex: 0xFF7A59)
  static let backgroundBg4 = Color(hex: 0x00A8E0)
  static let backgroundBg5 = Color(hex: 0xFAF8F5)
  static let backgroundBg6 = Color(hex: 0xFEFDFB)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x0C8C5E)
  static let textText2 = Color(hex: 0x121715)
  static let textText3 = Color(hex: 0x717D79)
  static let textText4 = Color(hex: 0xFFFFFF)
  static let textText5 = Color(hex: 0x969E9B)
  static let textText6 = Color(hex: 0x485450)
  static let textText7 = Color(hex: 0xCFCDCA)
}

// typography.body: family=inter size=50px weight=400 lineHeight=52px
