// Generated by designlang v7.0.0
// Source: https://v0.dev
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFD2D2D2)
    val SurfaceDefault = Color(0xFFF4F4F4)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFD2D2D2)
    val NeutralN100 = Color(0xFFD2D2D2)
    val NeutralN200 = Color(0xFF020202)
    val NeutralN300 = Color(0xFF222222)
    val NeutralN400 = Color(0xFFFFFFFF)
    val NeutralN500 = Color(0xFFF4F4F4)
    val NeutralN600 = Color(0xFF343434)
    val NeutralN700 = Color(0xFF646464)
    val NeutralN800 = Color(0xFFE2E2E2)
    val NeutralN900 = Color(0xFF959595)
    val BackgroundBg0 = Color(0xFFF4F4F4)
    val BackgroundBg1 = Color(0xFFFFFFFF)
    val BackgroundBg2 = Color(0xFFE2E2E2)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF020202)
    val TextText2 = Color(0xFF222222)
    val TextText3 = Color(0xFFFFFFFF)
    val TextText4 = Color(0xFF646464)
    val TextText5 = Color(0xFF343434)
    val SpacingS0 = 1.dp
    val SpacingS1 = 64.dp
    val SpacingS2 = 96.dp
    val SpacingS3 = 108.dp
    val SpacingS4 = 128.dp
    val SpacingS5 = 192.dp
    val SpacingS6 = 208.dp
    val RadiusR0 = 4.dp
    val RadiusR1 = 8.dp
    val RadiusR2 = 12.dp
    val RadiusR3 = 16.dp
    val RadiusR4 = 35.dp
}
