// Generated by designlang v7.0.0
// Source: https://discord.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF5865F2)
    val ActionSecondary = Color(0xFF35ED7E)
    val SurfaceDefault = Color(0xFF1A2081)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF5865F2)
    val BrandSecondary = Color(0xFF35ED7E)
    val NeutralN100 = Color(0xFF000000)
    val NeutralN200 = Color(0xFFFFFFFF)
    val NeutralN300 = Color(0xFF333333)
    val NeutralN400 = Color(0xFF23272A)
    val BackgroundBg0 = Color(0xFF1A2081)
    val BackgroundBg1 = Color(0xFF000000)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF333333)
    val TextText2 = Color(0xFFFFFFFF)
    val TextText3 = Color(0xFF23272A)
    val TextText4 = Color(0xFF5865F2)
    val SpacingS0 = 1.dp
    val SpacingS1 = 24.dp
    val SpacingS2 = 29.dp
    val SpacingS3 = 35.dp
    val SpacingS4 = 48.dp
    val SpacingS5 = 52.dp
    val SpacingS6 = 56.dp
    val SpacingS7 = 60.dp
    val SpacingS8 = 64.dp
    val SpacingS9 = 73.dp
    val SpacingS10 = 76.dp
    val SpacingS11 = 80.dp
    val SpacingS12 = 96.dp
    val SpacingS13 = 106.dp
    val SpacingS14 = 125.dp
    val SpacingS15 = 128.dp
    val SpacingS16 = 134.dp
    val SpacingS17 = 143.dp
    val SpacingS18 = 154.dp
    val SpacingS19 = 157.dp
    val SpacingS20 = 160.dp
    val SpacingS21 = 174.dp
    val SpacingS22 = 185.dp
    val SpacingS23 = 194.dp
    val SpacingS24 = 197.dp
    val SpacingS25 = 221.dp
    val SpacingS26 = 235.dp
    val SpacingS27 = 256.dp
    val SpacingS28 = 293.dp
    val SpacingS29 = 413.dp
    val SpacingS30 = 426.dp
    val SpacingS31 = 432.dp
    val SpacingS32 = 445.dp
    val RadiusR0 = 12.dp
    val RadiusR1 = 16.dp
    val RadiusR2 = 40.dp
    val RadiusR3 = 50.dp
    val RadiusR4 = 60.dp
    val RadiusR5 = 72.dp
    val RadiusR6 = 88.dp
}
