// Generated by designlang v7.0.0
// Source: https://raycast.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFFF6363);
  static const Color actionSecondary = Color(0xFF8CD6FF);
  static const Color surfaceDefault = Color(0xFF07080A);
  static const Color textBody = Color(0xFFFFFFFF);
  static const double spacingS0 = 1;
  static const double spacingS1 = 45;
  static const double spacingS2 = 56;
  static const double spacingS3 = 64;
  static const double spacingS4 = 72;
  static const double spacingS5 = 80;
  static const double spacingS6 = 96;
  static const double spacingS7 = 102;
  static const double spacingS8 = 120;
  static const double spacingS9 = 128;
  static const double spacingS10 = 137;
  static const double spacingS11 = 148;
  static const double spacingS12 = 169;
  static const double spacingS13 = 200;
  static const double spacingS14 = 212;
  static const double spacingS15 = 217;
  static const double spacingS16 = 224;
  static const double spacingS17 = 325;
  static const double spacingS18 = 370;
  static const double spacingS19 = 400;
  static const double spacingS20 = 409;
  static const double spacingS21 = 416;
  static const double radiusR0 = 2;
  static const double radiusR1 = 5;
  static const double radiusR2 = 8;
  static const double radiusR3 = 11;
  static const double radiusR4 = 16;
  static const double radiusR5 = 19;
  static const double radiusR6 = 22;
  static const double radiusR7 = 31;
  static const double radiusR8 = 36;
  static const double radiusR9 = 43;
  static const double radiusR10 = 86;
  static const double radiusR11 = 100;
  static const double radiusR12 = 1000;
  static const double radiusR13 = 99999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFFF6363);
  static const Color brandSecondary = Color(0xFF8CD6FF);
  static const Color neutralN100 = Color(0xFFFFFFFF);
  static const Color neutralN200 = Color(0xFF6A6B6C);
  static const Color neutralN300 = Color(0xFF9C9C9D);
  static const Color neutralN400 = Color(0xFF434345);
  static const Color neutralN500 = Color(0xFFE6E6E6);
  static const Color neutralN600 = Color(0xFF2F3031);
  static const Color neutralN700 = Color(0xFF1B1C1E);
  static const Color neutralN800 = Color(0xFF8E8C90);
  static const Color neutralN900 = Color(0xFF111214);
  static const Color backgroundBg0 = Color(0xFF07080A);
  static const Color backgroundBg1 = Color(0xFF000000);
  static const Color backgroundBg2 = Color(0xFFFFFFFF);
  static const Color backgroundBg3 = Color(0xFF9EBED7);
  static const Color backgroundBg4 = Color(0xFF111214);
  static const Color backgroundBg5 = Color(0xFFD72A2A);
  static const Color textText0 = Color(0xFFFFFFFF);
  static const Color textText1 = Color(0xFF9C9C9D);
  static const Color textText2 = Color(0xFF2F3031);
  static const Color textText3 = Color(0xFF6A6B6C);
  static const Color textText4 = Color(0xFFE6E6E6);
  static const Color textText5 = Color(0xFFFF6363);
  static const Color textText6 = Color(0xFF434345);
  static const Color textText7 = Color(0xFF8CD6FF);
  static const Color textText8 = Color(0xFF000000);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
