// Motion CSS emitter — `<host>-motion.css`.
//
// The framework-agnostic sibling of the Framer Motion / Motion One
// emitters. Anything that renders HTML can drop this file in: it ships
//   • custom properties — `--duration-*` and `--ease-*` from the live page
//   • `@keyframes` — fade-in / slide-up / scale-in / pop, plus any used
//     on-page @keyframes reconstructed from their real steps
//   • utility classes — `.mo-fade-in`, `.mo-slide-up`, … wired to the vars
//   • a `prefers-reduced-motion: reduce` guard so the whole thing degrades
//     to no-motion for users who ask for it (accessibility by default)

function bezier(raw) {
  if (!raw) return null;
  const m = String(raw).match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/i);
  if (m) return `cubic-bezier(${parseFloat(m[1])}, ${parseFloat(m[2])}, ${parseFloat(m[3])}, ${parseFloat(m[4])})`;
  const named = {
    linear: 'linear', ease: 'ease', 'ease-in': 'ease-in',
    'ease-out': 'ease-out', 'ease-in-out': 'ease-in-out',
  };
  return named[String(raw).trim()] || null;
}

// CSS identifiers: lowercase, hyphen-separated, never leading with a digit.
function kebab(s) {
  return String(s || '')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
    .replace(/^(\d)/, '_$1');
}

export function formatMotionCss(design) {
  const host = (() => { try { return new URL(design?.meta?.url).hostname.replace(/^www\./, ''); } catch { return 'site'; } })();
  const durations = Array.isArray(design?.motion?.durations) ? design.motion.durations : [];
  const easings   = Array.isArray(design?.motion?.easings)   ? design.motion.easings   : [];
  const springs   = Array.isArray(design?.motion?.springs)   ? design.motion.springs   : [];
  const keyframes = Array.isArray(design?.motion?.keyframes) ? design.motion.keyframes : [];

  // Default duration (the most common "medium" feel) and easing.
  const defaultDur = durations.length
    ? (durations[Math.min(2, durations.length - 1)].css || '300ms')
    : '300ms';
  const sortedEase = [...easings].sort((a, b) => (b.count || 0) - (a.count || 0));

  // Named easing variables, deduped by classified family.
  const easeEntries = [];
  sortedEase.forEach((e, i) => {
    const css = bezier(e.raw);
    if (!css) return;
    const key = e.family && e.family !== 'custom' ? kebab(e.family) : `custom-${i + 1}`;
    if (easeEntries.find((x) => x.key === key)) return;
    easeEntries.push({ key, css, count: e.count });
  });
  const firstSpring = springs.map(s => bezier(s.raw)).find(Boolean);
  if (firstSpring) easeEntries.push({ key: 'spring', css: firstSpring, count: 0 });
  if (easeEntries.length === 0) easeEntries.push({ key: 'standard', css: 'cubic-bezier(0.25, 0.1, 0.25, 1)', count: 0 });
  const defaultEaseVar = easeEntries[0].key;

  const lines = [
    '/* Motion CSS — generated by designlang (motionlang)',
    ` * Source: ${design?.meta?.url || host}`,
    ` * ${new Date().toISOString()}`,
    ' *',
    ' *   <link rel="stylesheet" href="./' + host + '-motion.css">',
    ' *   <div class="mo-slide-up">…</div>',
    ' */',
    '',
    ':root {',
  ];

  if (durations.length) {
    for (const d of durations) lines.push(`  --duration-${kebab(d.name || `ms-${d.ms}`)}: ${d.css};`);
  } else {
    lines.push('  --duration-fast: 150ms;', '  --duration-base: 300ms;', '  --duration-slow: 500ms;');
  }
  for (const { key, css, count } of easeEntries) {
    lines.push(`  --ease-${key}: ${css};${count ? ` /* ${count}× on page */` : ''}`);
  }
  lines.push('}', '');

  // Built-in keyframes — the same vocabulary the JS emitters expose.
  lines.push('@keyframes fade-in   { from { opacity: 0; }                              to { opacity: 1; } }');
  lines.push('@keyframes slide-up  { from { opacity: 0; transform: translateY(16px); } to { opacity: 1; transform: none; } }');
  lines.push('@keyframes scale-in  { from { opacity: 0; transform: scale(0.96); }      to { opacity: 1; transform: none; } }');
  lines.push('@keyframes pop       { 0% { transform: scale(0.9); } 60% { transform: scale(1.03); } 100% { transform: scale(1); } }');
  lines.push('');

  // Reconstructed @keyframes that the page actually attached to elements.
  const usedKeyframes = keyframes.filter(k => k.used && k.steps && k.steps.length);
  for (const kf of usedKeyframes.slice(0, 12)) {
    const name = kebab(kf.name);
    if (['fade-in', 'slide-up', 'scale-in', 'pop'].includes(name)) continue;
    const steps = kf.steps
      .map(s => {
        const offset = s.offset === 'from' ? '0%' : s.offset === 'to' ? '100%' : s.offset;
        const body = String(s.style || '').split(';').map(x => x.trim()).filter(Boolean).join('; ');
        return offset && body ? `  ${offset} { ${body}; }` : '';
      })
      .filter(Boolean);
    if (!steps.length) continue;
    lines.push(`@keyframes ${name} {`);
    lines.push(steps.join('\n'));
    lines.push('}', '');
  }

  // Utility classes wired to the extracted timing.
  lines.push('.mo-animate,');
  lines.push('[class^="mo-"], [class*=" mo-"] {');
  lines.push(`  animation-duration: var(--duration-${kebab(durations[Math.min(2, durations.length - 1)]?.name || 'base')}, ${defaultDur});`);
  lines.push(`  animation-timing-function: var(--ease-${defaultEaseVar});`);
  lines.push('  animation-fill-mode: both;');
  lines.push('}', '');

  const utility = (cls, kf, ease) => {
    lines.push(`.mo-${cls} { animation-name: ${kf};${ease ? ` animation-timing-function: var(--ease-${ease});` : ''} }`);
  };
  utility('fade-in', 'fade-in');
  utility('slide-up', 'slide-up');
  utility('scale-in', 'scale-in');
  utility('pop', 'pop', firstSpring ? 'spring' : defaultEaseVar);
  lines.push('');

  // Accessibility: honour reduced-motion globally.
  lines.push('@media (prefers-reduced-motion: reduce) {');
  lines.push('  *, ::before, ::after {');
  lines.push('    animation-duration: 0.01ms !important;');
  lines.push('    animation-iteration-count: 1 !important;');
  lines.push('    transition-duration: 0.01ms !important;');
  lines.push('    scroll-behavior: auto !important;');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
