// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://retool.com
// Generated: 2026-06-25T08:31:29.685Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#e9ebdf' | '#151515' | '#ffffff' | '#cbccc4' | '#242424' | '#8b867f' | '#f7f8f4' | '#b6b8af' | '#000000' | '#d9d9d9' | '#433e38' | '#518dd2' | '#0e352c';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'saansFont' | 'pxGroteskFont';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '380' | '300';

export type SpacingToken = '1px' | '20px' | '24px' | '28px' | '32px' | '40px' | '56px' | '64px' | '71px' | '80px' | '120px' | '158px' | '384px';

export type RadiusToken = '4px' | '8px' | '12px' | '16px' | '20px' | '24px' | '36px' | '50px' | '9999px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
