// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://supabase.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x72E3AD)
  static let actionSecondary = Color(hex: 0x00BB68)
  static let surfaceDefault = Color(hex: 0xFCFCFC)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 40
  static let spacingS2: CGFloat = 48
  static let spacingS3: CGFloat = 64
  static let spacingS4: CGFloat = 90
  static let spacingS5: CGFloat = 112
  static let spacingS6: CGFloat = 128
  static let spacingS7: CGFloat = 157
  static let spacingS8: CGFloat = 208
  static let spacingS9: CGFloat = 246
  static let spacingS10: CGFloat = 304

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 6
  static let radiusR1: CGFloat = 11
  static let radiusR2: CGFloat = 16
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x72E3AD)
  static let brandSecondary = Color(hex: 0x00BB68)
  static let neutralN100 = Color(hex: 0xDFDFDF)
  static let neutralN200 = Color(hex: 0x171717)
  static let neutralN300 = Color(hex: 0x525252)
  static let neutralN400 = Color(hex: 0x707070)
  static let neutralN500 = Color(hex: 0xFFFFFF)
  static let neutralN600 = Color(hex: 0xB2B2B2)
  static let neutralN700 = Color(hex: 0x000000)
  static let neutralN800 = Color(hex: 0xC7C7C7)
  static let neutralN900 = Color(hex: 0xEDEDED)
  static let neutralN1000 = Color(hex: 0xD4D4D4)
  static let neutralN1100 = Color(hex: 0x292929)
  static let backgroundBg0 = Color(hex: 0xFCFCFC)
  static let backgroundBg1 = Color(hex: 0xF8F8F8)
  static let backgroundBg2 = Color(hex: 0xFFFFFF)
  static let backgroundBg3 = Color(hex: 0xFDFDFD)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x171717)
  static let textText2 = Color(hex: 0x525252)
  static let textText3 = Color(hex: 0x707070)
  static let textText4 = Color(hex: 0x3FCF8E)
  static let textText5 = Color(hex: 0xB2B2B2)
  static let textText6 = Color(hex: 0x00BB68)
}

// typography.body: family=Circular size=72px weight=400 lineHeight=72px
