// Generated by designlang v7.0.0
// Source: https://posthog.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFE1D7C2)
    val ActionSecondary = Color(0xFFEB9D2A)
    val SurfaceDefault = Color(0xFFE5E7E0)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFE1D7C2)
    val BrandSecondary = Color(0xFFEB9D2A)
    val NeutralN100 = Color(0xFF000000)
    val NeutralN200 = Color(0xFF4D4F46)
    val NeutralN300 = Color(0xFF374151)
    val NeutralN400 = Color(0xFF23251D)
    val NeutralN500 = Color(0xFF9EA096)
    val NeutralN600 = Color(0xFF65675E)
    val NeutralN700 = Color(0xFFBFC1B7)
    val NeutralN800 = Color(0xFFFFFFFF)
    val NeutralN900 = Color(0xFFB6B7AF)
    val NeutralN1000 = Color(0xFF131316)
    val NeutralN1100 = Color(0xFFD0D1C9)
    val NeutralN1200 = Color(0xFF73756B)
    val BackgroundBg0 = Color(0xFFE5E7E0)
    val BackgroundBg1 = Color(0xFFE1D7C2)
    val BackgroundBg2 = Color(0xFFFFFFFF)
    val BackgroundBg3 = Color(0xFFEEEFE9)
    val BackgroundBg4 = Color(0xFFFDFDF8)
    val BackgroundBg5 = Color(0xFF2F80FA)
    val BackgroundBg6 = Color(0xFFF3F4F0)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF23251D)
    val TextText2 = Color(0xFF73756B)
    val TextText3 = Color(0xFF65675E)
    val TextText4 = Color(0xFF4D4F46)
    val TextText5 = Color(0xFF9EA096)
    val TextText6 = Color(0xFF374151)
    val TextText7 = Color(0xFF111827)
    val TextText8 = Color(0xFFFFFFFF)
    val TextText9 = Color(0xFFB62AD9)
    val SpacingS0 = 1.dp
    val SpacingS1 = 20.dp
    val SpacingS2 = 32.dp
    val SpacingS3 = 48.dp
    val SpacingS4 = 64.dp
    val SpacingS5 = 120.dp
    val SpacingS6 = 144.dp
    val SpacingS7 = 220.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 5.dp
    val RadiusR2 = 8.dp
    val RadiusR3 = 9999.dp
}
