// Generated by designlang v7.0.0
// Source: https://netflix.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFE50914);
  static const Color actionSecondary = Color(0xFF3860BE);
  static const Color surfaceDefault = Color(0xFF000000);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 10;
  static const double spacingS2 = 12;
  static const double spacingS3 = 20;
  static const double spacingS4 = 22;
  static const double spacingS5 = 24;
  static const double spacingS6 = 27;
  static const double spacingS7 = 30;
  static const double spacingS8 = 32;
  static const double spacingS9 = 34;
  static const double spacingS10 = 64;
  static const double spacingS11 = 96;
  static const double spacingS12 = 100;
  static const double spacingS13 = 128;
  static const double spacingS14 = 148;
  static const double spacingS15 = 314;
  static const double radiusR0 = 2;
  static const double radiusR1 = 8;
  static const double radiusR2 = 16;
  static const double radiusR3 = 20;
  static const double radiusR4 = 50;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFE50914);
  static const Color brandSecondary = Color(0xFF3860BE);
  static const Color neutralN100 = Color(0xFFFFFFFF);
  static const Color neutralN200 = Color(0xFF000000);
  static const Color neutralN300 = Color(0xFF333333);
  static const Color neutralN400 = Color(0xFF232323);
  static const Color neutralN500 = Color(0xFF414141);
  static const Color neutralN600 = Color(0xFF555555);
  static const Color neutralN700 = Color(0xFFF4F4F4);
  static const Color neutralN800 = Color(0xFF161616);
  static const Color neutralN900 = Color(0xFF808080);
  static const Color neutralN1000 = Color(0xFFC1C1C1);
  static const Color neutralN1100 = Color(0xFF707070);
  static const Color neutralN1200 = Color(0xFFD8D8D8);
  static const Color backgroundBg0 = Color(0xFF000000);
  static const Color backgroundBg1 = Color(0xFF2D2D2D);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFFFFFFFF);
  static const Color textText2 = Color(0xFFE50914);
  static const Color textText3 = Color(0xFF414141);
  static const Color textText4 = Color(0xFF333333);
  static const Color textText5 = Color(0xFF555555);
  static const Color textText6 = Color(0xFF3860BE);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
