// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://clerk.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x6C47FF)
  static let actionSecondary = Color(hex: 0x1CC4FF)
  static let surfaceDefault = Color(hex: 0xF7F7F8)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 46
  static let spacingS2: CGFloat = 56
  static let spacingS3: CGFloat = 76
  static let spacingS4: CGFloat = 94
  static let spacingS5: CGFloat = 128
  static let spacingS6: CGFloat = 140
  static let spacingS7: CGFloat = 151
  static let spacingS8: CGFloat = 158
  static let spacingS9: CGFloat = 167
  static let spacingS10: CGFloat = 172
  static let spacingS11: CGFloat = 192
  static let spacingS12: CGFloat = 220
  static let spacingS13: CGFloat = 259
  static let spacingS14: CGFloat = 272
  static let spacingS15: CGFloat = 302
  static let spacingS16: CGFloat = 320

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 5
  static let radiusR2: CGFloat = 8
  static let radiusR3: CGFloat = 12
  static let radiusR4: CGFloat = 16
  static let radiusR5: CGFloat = 38
  static let radiusR6: CGFloat = 44
  static let radiusR7: CGFloat = 50
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x6C47FF)
  static let brandSecondary = Color(hex: 0x1CC4FF)
  static let neutralN100 = Color(hex: 0xD9D9DE)
  static let neutralN200 = Color(hex: 0x000000)
  static let neutralN300 = Color(hex: 0xFFFFFF)
  static let neutralN400 = Color(hex: 0x131316)
  static let neutralN500 = Color(hex: 0x747686)
  static let neutralN600 = Color(hex: 0x5E5F6E)
  static let neutralN700 = Color(hex: 0x2F3037)
  static let neutralN800 = Color(hex: 0x9394A1)
  static let neutralN900 = Color(hex: 0x696A78)
  static let neutralN1000 = Color(hex: 0xEEEEF0)
  static let neutralN1100 = Color(hex: 0x212126)
  static let neutralN1200 = Color(hex: 0x42434D)
  static let neutralN1300 = Color(hex: 0xB7B8C2)
  static let neutralN1400 = Color(hex: 0x4A4C5B)
  static let backgroundBg0 = Color(hex: 0xF7F7F8)
  static let backgroundBg1 = Color(hex: 0xF8F8F8)
  static let backgroundBg2 = Color(hex: 0x131316)
  static let backgroundBg3 = Color(hex: 0xFFFFFF)
  static let backgroundBg4 = Color(hex: 0x212126)
  static let backgroundBg5 = Color(hex: 0x2D2E3D)
  static let backgroundBg6 = Color(hex: 0x29292E)
  static let backgroundBg7 = Color(hex: 0x25252A)
  static let backgroundBg8 = Color(hex: 0x2F3037)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0xFFFFFF)
  static let textText2 = Color(hex: 0x131316)
  static let textText3 = Color(hex: 0x747686)
  static let textText4 = Color(hex: 0x5E5F6E)
  static let textText5 = Color(hex: 0x212126)
  static let textText6 = Color(hex: 0x6C47FF)
  static let textText7 = Color(hex: 0x9394A1)
  static let textText8 = Color(hex: 0x696A78)
  static let textText9 = Color(hex: 0x42434D)
}

// typography.body: family=geistNumbers size=64px weight=700 lineHeight=72px
