// Generated by designlang v7.0.0
// Source: https://loom.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF1868DB);
  static const Color actionSecondary = Color(0xFFFFAB00);
  static const Color surfaceDefault = Color(0xFFFFFFFF);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 15;
  static const double spacingS2 = 23;
  static const double spacingS3 = 30;
  static const double spacingS4 = 35;
  static const double spacingS5 = 40;
  static const double spacingS6 = 48;
  static const double spacingS7 = 56;
  static const double spacingS8 = 64;
  static const double spacingS9 = 80;
  static const double spacingS10 = 84;
  static const double spacingS11 = 103;
  static const double spacingS12 = 154;
  static const double spacingS13 = 192;
  static const double spacingS14 = 269;
  static const double radiusR0 = 1;
  static const double radiusR1 = 6;
  static const double radiusR2 = 12;
  static const double radiusR3 = 16;
  static const double radiusR4 = 24;
  static const double radiusR5 = 39;
  static const double radiusR6 = 50;
  static const double radiusR7 = 66;
  static const double radiusR8 = 9999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF1868DB);
  static const Color brandSecondary = Color(0xFFFFAB00);
  static const Color neutralN100 = Color(0xFF292A2E);
  static const Color neutralN200 = Color(0xFF000000);
  static const Color neutralN300 = Color(0xFFFFFFFF);
  static const Color neutralN400 = Color(0xFF696969);
  static const Color neutralN500 = Color(0xFF555555);
  static const Color neutralN600 = Color(0xFFF8F8F8);
  static const Color neutralN700 = Color(0xFF7D818A);
  static const Color neutralN800 = Color(0xFFD8D8D8);
  static const Color neutralN900 = Color(0xFFBBBBBB);
  static const Color backgroundBg0 = Color(0xFFFFFFFF);
  static const Color backgroundBg1 = Color(0xFF101214);
  static const Color backgroundBg2 = Color(0xFF1868DB);
  static const Color backgroundBg3 = Color(0xFFEED7FC);
  static const Color backgroundBg4 = Color(0xFFEFFFD6);
  static const Color backgroundBg5 = Color(0xFFF8EEFE);
  static const Color backgroundBg6 = Color(0xFFE9F2FE);
  static const Color backgroundBg7 = Color(0xFFFFF5D4);
  static const Color backgroundBg8 = Color(0xFF123263);
  static const Color backgroundBg9 = Color(0xFF1558BC);
  static const Color backgroundBg10 = Color(0xFF292A2E);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF292A2E);
  static const Color textText2 = Color(0xFF7D818A);
  static const Color textText3 = Color(0xFF101214);
  static const Color textText4 = Color(0xFFFFFFFF);
  static const Color textText5 = Color(0xFFFF613D);
  static const Color textText6 = Color(0xFF1868DB);
  static const Color textText7 = Color(0xFFBF63F3);
  static const Color textText8 = Color(0xFFC97CF4);
  static const Color textText9 = Color(0xFF48245D);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
