// Generated by designlang v7.0.0
// Source: https://discord.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF5865F2);
  static const Color actionSecondary = Color(0xFF35ED7E);
  static const Color surfaceDefault = Color(0xFF1A2081);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 24;
  static const double spacingS2 = 29;
  static const double spacingS3 = 35;
  static const double spacingS4 = 48;
  static const double spacingS5 = 52;
  static const double spacingS6 = 56;
  static const double spacingS7 = 60;
  static const double spacingS8 = 64;
  static const double spacingS9 = 73;
  static const double spacingS10 = 76;
  static const double spacingS11 = 80;
  static const double spacingS12 = 96;
  static const double spacingS13 = 106;
  static const double spacingS14 = 125;
  static const double spacingS15 = 128;
  static const double spacingS16 = 134;
  static const double spacingS17 = 143;
  static const double spacingS18 = 154;
  static const double spacingS19 = 157;
  static const double spacingS20 = 160;
  static const double spacingS21 = 174;
  static const double spacingS22 = 185;
  static const double spacingS23 = 194;
  static const double spacingS24 = 197;
  static const double spacingS25 = 221;
  static const double spacingS26 = 235;
  static const double spacingS27 = 256;
  static const double spacingS28 = 293;
  static const double spacingS29 = 413;
  static const double spacingS30 = 426;
  static const double spacingS31 = 432;
  static const double spacingS32 = 445;
  static const double radiusR0 = 12;
  static const double radiusR1 = 16;
  static const double radiusR2 = 40;
  static const double radiusR3 = 50;
  static const double radiusR4 = 60;
  static const double radiusR5 = 72;
  static const double radiusR6 = 88;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF5865F2);
  static const Color brandSecondary = Color(0xFF35ED7E);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFF333333);
  static const Color neutralN400 = Color(0xFF23272A);
  static const Color backgroundBg0 = Color(0xFF1A2081);
  static const Color backgroundBg1 = Color(0xFF000000);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF333333);
  static const Color textText2 = Color(0xFFFFFFFF);
  static const Color textText3 = Color(0xFF23272A);
  static const Color textText4 = Color(0xFF5865F2);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
