// Generated by designlang v7.0.0
// Source: https://framer.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF0066FF)
    val ActionSecondary = Color(0xFF0000EE)
    val SurfaceDefault = Color(0xFF000000)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF0066FF)
    val BrandSecondary = Color(0xFF0000EE)
    val NeutralN100 = Color(0xFF000000)
    val NeutralN200 = Color(0xFFFFFFFF)
    val NeutralN300 = Color(0xFF999999)
    val NeutralN400 = Color(0xFF242424)
    val NeutralN500 = Color(0xFF666666)
    val NeutralN600 = Color(0xFF111111)
    val NeutralN700 = Color(0xFFCCCCCC)
    val NeutralN800 = Color(0xFF303030)
    val NeutralN900 = Color(0xFF878787)
    val NeutralN1000 = Color(0xFF444444)
    val NeutralN1100 = Color(0xFF1A1A1A)
    val NeutralN1200 = Color(0xFFEEEEEE)
    val BackgroundBg0 = Color(0xFF000000)
    val BackgroundBg1 = Color(0xFF111111)
    val BackgroundBg2 = Color(0xFF171717)
    val BackgroundBg3 = Color(0xFF0099FF)
    val BackgroundBg4 = Color(0xFFFFFFFF)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF0000EE)
    val TextText2 = Color(0xFFFFFFFF)
    val TextText3 = Color(0xFF999999)
    val TextText4 = Color(0xFF9A9997)
    val TextText5 = Color(0xFF666666)
    val TextText6 = Color(0xFF444444)
    val TextText7 = Color(0xFFCCCCCC)
    val TextText8 = Color(0xFF0099FF)
    val TextText9 = Color(0xFF00BB88)
    val SpacingS0 = 1.dp
    val SpacingS1 = 20.dp
    val SpacingS2 = 25.dp
    val SpacingS3 = 30.dp
    val SpacingS4 = 40.dp
    val SpacingS5 = 45.dp
    val SpacingS6 = 50.dp
    val SpacingS7 = 55.dp
    val SpacingS8 = 60.dp
    val SpacingS9 = 64.dp
    val SpacingS10 = 100.dp
    val SpacingS11 = 120.dp
    val SpacingS12 = 160.dp
    val SpacingS13 = 200.dp
    val RadiusR0 = 1.dp
    val RadiusR1 = 4.dp
    val RadiusR2 = 7.dp
    val RadiusR3 = 10.dp
    val RadiusR4 = 14.dp
    val RadiusR5 = 18.dp
    val RadiusR6 = 21.dp
    val RadiusR7 = 25.dp
    val RadiusR8 = 30.dp
    val RadiusR9 = 50.dp
    val RadiusR10 = 100.dp
}
