// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://netflix.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xE50914)
  static let actionSecondary = Color(hex: 0x3860BE)
  static let surfaceDefault = Color(hex: 0x000000)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 10
  static let spacingS2: CGFloat = 12
  static let spacingS3: CGFloat = 20
  static let spacingS4: CGFloat = 22
  static let spacingS5: CGFloat = 24
  static let spacingS6: CGFloat = 27
  static let spacingS7: CGFloat = 30
  static let spacingS8: CGFloat = 32
  static let spacingS9: CGFloat = 34
  static let spacingS10: CGFloat = 64
  static let spacingS11: CGFloat = 96
  static let spacingS12: CGFloat = 100
  static let spacingS13: CGFloat = 128
  static let spacingS14: CGFloat = 148
  static let spacingS15: CGFloat = 314

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 8
  static let radiusR2: CGFloat = 16
  static let radiusR3: CGFloat = 20
  static let radiusR4: CGFloat = 50
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xE50914)
  static let brandSecondary = Color(hex: 0x3860BE)
  static let neutralN100 = Color(hex: 0xFFFFFF)
  static let neutralN200 = Color(hex: 0x000000)
  static let neutralN300 = Color(hex: 0x333333)
  static let neutralN400 = Color(hex: 0x232323)
  static let neutralN500 = Color(hex: 0x414141)
  static let neutralN600 = Color(hex: 0x555555)
  static let neutralN700 = Color(hex: 0xF4F4F4)
  static let neutralN800 = Color(hex: 0x161616)
  static let neutralN900 = Color(hex: 0x808080)
  static let neutralN1000 = Color(hex: 0xC1C1C1)
  static let neutralN1100 = Color(hex: 0x707070)
  static let neutralN1200 = Color(hex: 0xD8D8D8)
  static let backgroundBg0 = Color(hex: 0x000000)
  static let backgroundBg1 = Color(hex: 0x2D2D2D)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0xFFFFFF)
  static let textText2 = Color(hex: 0xE50914)
  static let textText3 = Color(hex: 0x414141)
  static let textText4 = Color(hex: 0x333333)
  static let textText5 = Color(hex: 0x555555)
  static let textText6 = Color(hex: 0x3860BE)
}

// typography.body: family=Netflix Sans size=100px weight=400 lineHeight=normal
