// Generated by designlang v7.0.0
// Source: https://netflix.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFE50914)
    val ActionSecondary = Color(0xFF3860BE)
    val SurfaceDefault = Color(0xFF000000)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFE50914)
    val BrandSecondary = Color(0xFF3860BE)
    val NeutralN100 = Color(0xFFFFFFFF)
    val NeutralN200 = Color(0xFF000000)
    val NeutralN300 = Color(0xFF333333)
    val NeutralN400 = Color(0xFF232323)
    val NeutralN500 = Color(0xFF414141)
    val NeutralN600 = Color(0xFF555555)
    val NeutralN700 = Color(0xFFF4F4F4)
    val NeutralN800 = Color(0xFF161616)
    val NeutralN900 = Color(0xFF808080)
    val NeutralN1000 = Color(0xFFC1C1C1)
    val NeutralN1100 = Color(0xFF707070)
    val NeutralN1200 = Color(0xFFD8D8D8)
    val BackgroundBg0 = Color(0xFF000000)
    val BackgroundBg1 = Color(0xFF2D2D2D)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFFFFFFFF)
    val TextText2 = Color(0xFFE50914)
    val TextText3 = Color(0xFF414141)
    val TextText4 = Color(0xFF333333)
    val TextText5 = Color(0xFF555555)
    val TextText6 = Color(0xFF3860BE)
    val SpacingS0 = 1.dp
    val SpacingS1 = 10.dp
    val SpacingS2 = 12.dp
    val SpacingS3 = 20.dp
    val SpacingS4 = 22.dp
    val SpacingS5 = 24.dp
    val SpacingS6 = 27.dp
    val SpacingS7 = 30.dp
    val SpacingS8 = 32.dp
    val SpacingS9 = 34.dp
    val SpacingS10 = 64.dp
    val SpacingS11 = 96.dp
    val SpacingS12 = 100.dp
    val SpacingS13 = 128.dp
    val SpacingS14 = 148.dp
    val SpacingS15 = 314.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 8.dp
    val RadiusR2 = 16.dp
    val RadiusR3 = 20.dp
    val RadiusR4 = 50.dp
}
