// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://postman.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xE05320)
  static let actionSecondary = Color(hex: 0x007BFF)
  static let surfaceDefault = Color(hex: 0xFFFFFF)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 20
  static let spacingS2: CGFloat = 24
  static let spacingS3: CGFloat = 40
  static let spacingS4: CGFloat = 50
  static let spacingS5: CGFloat = 60
  static let spacingS6: CGFloat = 64
  static let spacingS7: CGFloat = 80
  static let spacingS8: CGFloat = 120
  static let spacingS9: CGFloat = 224
  static let spacingS10: CGFloat = 252

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 3
  static let radiusR1: CGFloat = 10
  static let radiusR2: CGFloat = 15
  static let radiusR3: CGFloat = 20
  static let radiusR4: CGFloat = 9999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xE05320)
  static let brandSecondary = Color(hex: 0x007BFF)
  static let neutralN100 = Color(hex: 0x212121)
  static let neutralN200 = Color(hex: 0x000000)
  static let neutralN300 = Color(hex: 0x707070)
  static let neutralN400 = Color(hex: 0xFFFFFF)
  static let neutralN500 = Color(hex: 0x5C5C5C)
  static let neutralN600 = Color(hex: 0xE6E6E6)
  static let neutralN700 = Color(hex: 0x09070D)
  static let neutralN800 = Color(hex: 0x8A8A8A)
  static let neutralN900 = Color(hex: 0xCFCFCF)
  static let backgroundBg0 = Color(hex: 0xFFFFFF)
  static let backgroundBg1 = Color(hex: 0xF9F8F7)
  static let backgroundBg2 = Color(hex: 0xFF6C37)
  static let backgroundBg3 = Color(hex: 0x140B1E)
  static let backgroundBg4 = Color(hex: 0x09070D)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x212121)
  static let textText2 = Color(hex: 0x0265D2)
  static let textText3 = Color(hex: 0x6B6B6B)
  static let textText4 = Color(hex: 0xE05320)
  static let textText5 = Color(hex: 0x5C5C5C)
  static let textText6 = Color(hex: 0xFFFFFF)
  static let textText7 = Color(hex: 0x707070)
  static let textText8 = Color(hex: 0x007BFF)
}

// typography.body: family=inter size=55px weight=600 lineHeight=49.5px
