// Generated by designlang v7.0.0
// Source: https://v0.dev
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFD2D2D2);
  static const Color surfaceDefault = Color(0xFFF4F4F4);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 64;
  static const double spacingS2 = 96;
  static const double spacingS3 = 108;
  static const double spacingS4 = 128;
  static const double spacingS5 = 192;
  static const double spacingS6 = 208;
  static const double radiusR0 = 4;
  static const double radiusR1 = 8;
  static const double radiusR2 = 12;
  static const double radiusR3 = 16;
  static const double radiusR4 = 35;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFD2D2D2);
  static const Color neutralN100 = Color(0xFFD2D2D2);
  static const Color neutralN200 = Color(0xFF020202);
  static const Color neutralN300 = Color(0xFF222222);
  static const Color neutralN400 = Color(0xFFFFFFFF);
  static const Color neutralN500 = Color(0xFFF4F4F4);
  static const Color neutralN600 = Color(0xFF343434);
  static const Color neutralN700 = Color(0xFF646464);
  static const Color neutralN800 = Color(0xFFE2E2E2);
  static const Color neutralN900 = Color(0xFF959595);
  static const Color backgroundBg0 = Color(0xFFF4F4F4);
  static const Color backgroundBg1 = Color(0xFFFFFFFF);
  static const Color backgroundBg2 = Color(0xFFE2E2E2);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF020202);
  static const Color textText2 = Color(0xFF222222);
  static const Color textText3 = Color(0xFFFFFFFF);
  static const Color textText4 = Color(0xFF646464);
  static const Color textText5 = Color(0xFF343434);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
