// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://posthog.com
// Generated: 2026-06-25T08:30:20.026Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#4d4f46' | '#374151' | '#23251d' | '#111827' | '#9ea096' | '#f7a501' | '#2f80fa' | '#65675e' | '#30abc6' | '#bfc1b7' | '#b62ad9' | '#ffffff' | '#36c46f' | '#6aa84f' | '#eeefe9' | '#e1d7c2' | '#29dbbb' | '#b17816' | '#b6b7af' | '#131316' | '#f54e00' | '#d0d1c9' | '#73756b' | '#eb9d2a' | '#e5e7e0' | '#cd8407' | '#6c47ff' | '#bab1ff';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'IBM Plex Sans Variable' | 'Open Runde' | 'Source Code Pro';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700' | '800';

export type SpacingToken = '1px' | '20px' | '32px' | '48px' | '64px' | '120px' | '144px' | '220px';

export type RadiusToken = '2px' | '5px' | '8px' | '9999px';

export type DurationToken = '150ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
