// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://mintlify.com
// Generated: 2026-06-25T08:30:14.504Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#ffffff' | '#121715' | '#969e9b' | '#485450' | '#faf8f5' | '#0c8c5e' | '#1fa77a' | '#717d79' | '#cfcdca' | '#16a34a' | '#ef6333' | '#004cff' | '#ff7a59' | '#00a8e0';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'inter' | 'paperMono' | 'arizonaFlare';
export type FontSizeToken   = never;
export type FontWeightToken = '500' | '400';

export type SpacingToken = '4px' | '40px' | '48px' | '64px' | '80px' | '93px' | '104px' | '128px' | '160px' | '266px' | '290px' | '298px';

export type RadiusToken = '2px' | '6px' | '12px' | '24px';

export type DurationToken = '55ms' | '100ms' | '165ms' | '280ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
