// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://raycast.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xFF6363)
  static let actionSecondary = Color(hex: 0x8CD6FF)
  static let surfaceDefault = Color(hex: 0x07080A)
  static let textBody = Color(hex: 0xFFFFFF)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 45
  static let spacingS2: CGFloat = 56
  static let spacingS3: CGFloat = 64
  static let spacingS4: CGFloat = 72
  static let spacingS5: CGFloat = 80
  static let spacingS6: CGFloat = 96
  static let spacingS7: CGFloat = 102
  static let spacingS8: CGFloat = 120
  static let spacingS9: CGFloat = 128
  static let spacingS10: CGFloat = 137
  static let spacingS11: CGFloat = 148
  static let spacingS12: CGFloat = 169
  static let spacingS13: CGFloat = 200
  static let spacingS14: CGFloat = 212
  static let spacingS15: CGFloat = 217
  static let spacingS16: CGFloat = 224
  static let spacingS17: CGFloat = 325
  static let spacingS18: CGFloat = 370
  static let spacingS19: CGFloat = 400
  static let spacingS20: CGFloat = 409
  static let spacingS21: CGFloat = 416

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 5
  static let radiusR2: CGFloat = 8
  static let radiusR3: CGFloat = 11
  static let radiusR4: CGFloat = 16
  static let radiusR5: CGFloat = 19
  static let radiusR6: CGFloat = 22
  static let radiusR7: CGFloat = 31
  static let radiusR8: CGFloat = 36
  static let radiusR9: CGFloat = 43
  static let radiusR10: CGFloat = 86
  static let radiusR11: CGFloat = 100
  static let radiusR12: CGFloat = 1000
  static let radiusR13: CGFloat = 99999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xFF6363)
  static let brandSecondary = Color(hex: 0x8CD6FF)
  static let neutralN100 = Color(hex: 0xFFFFFF)
  static let neutralN200 = Color(hex: 0x6A6B6C)
  static let neutralN300 = Color(hex: 0x9C9C9D)
  static let neutralN400 = Color(hex: 0x434345)
  static let neutralN500 = Color(hex: 0xE6E6E6)
  static let neutralN600 = Color(hex: 0x2F3031)
  static let neutralN700 = Color(hex: 0x1B1C1E)
  static let neutralN800 = Color(hex: 0x8E8C90)
  static let neutralN900 = Color(hex: 0x111214)
  static let backgroundBg0 = Color(hex: 0x07080A)
  static let backgroundBg1 = Color(hex: 0x000000)
  static let backgroundBg2 = Color(hex: 0xFFFFFF)
  static let backgroundBg3 = Color(hex: 0x9EBED7)
  static let backgroundBg4 = Color(hex: 0x111214)
  static let backgroundBg5 = Color(hex: 0xD72A2A)
  static let textText0 = Color(hex: 0xFFFFFF)
  static let textText1 = Color(hex: 0x9C9C9D)
  static let textText2 = Color(hex: 0x2F3031)
  static let textText3 = Color(hex: 0x6A6B6C)
  static let textText4 = Color(hex: 0xE6E6E6)
  static let textText5 = Color(hex: 0xFF6363)
  static let textText6 = Color(hex: 0x434345)
  static let textText7 = Color(hex: 0x8CD6FF)
  static let textText8 = Color(hex: 0x000000)
}

// typography.body: family=Inter size=64px weight=600 lineHeight=70.4px
