// Generated by designlang v7.0.0
// Source: https://railway.app
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF59497A);
  static const Color actionSecondary = Color(0xFF291839);
  static const Color surfaceDefault = Color(0xFF13111C);
  static const Color textBody = Color(0xFFFFFFFF);
  static const double spacingS0 = 4;
  static const double spacingS1 = 60;
  static const double spacingS2 = 80;
  static const double spacingS3 = 96;
  static const double spacingS4 = 128;
  static const double spacingS5 = 159;
  static const double spacingS6 = 235;
  static const double spacingS7 = 262;
  static const double radiusR0 = 4;
  static const double radiusR1 = 8;
  static const double radiusR2 = 16;
  static const double radiusR3 = 50;
  static const double radiusR4 = 9999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF59497A);
  static const Color brandSecondary = Color(0xFF291839);
  static const Color neutralN100 = Color(0xFF33323E);
  static const Color neutralN200 = Color(0xFFF7F7F8);
  static const Color neutralN300 = Color(0xFF545260);
  static const Color neutralN400 = Color(0xFFA1A0AB);
  static const Color neutralN500 = Color(0xFF609F89);
  static const Color neutralN600 = Color(0xFF878593);
  static const Color neutralN700 = Color(0xFFDCDCE0);
  static const Color neutralN800 = Color(0xFF000000);
  static const Color backgroundBg0 = Color(0xFF13111C);
  static const Color backgroundBg1 = Color(0xFF000000);
  static const Color backgroundBg2 = Color(0xFF180D43);
  static const Color backgroundBg3 = Color(0xFF1F132A);
  static const Color backgroundBg4 = Color(0xFF0D0C14);
  static const Color backgroundBg5 = Color(0xFF1B2132);
  static const Color backgroundBg6 = Color(0xFF1F2B2E);
  static const Color textText0 = Color(0xFFFFFFFF);
  static const Color textText1 = Color(0xFF13111C);
  static const Color textText2 = Color(0xFFA667E4);
  static const Color textText3 = Color(0xFFF7F7F8);
  static const Color textText4 = Color(0xFFDCDCE0);
  static const Color textText5 = Color(0xFFA1A0AB);
  static const Color textText6 = Color(0xFF545260);
  static const Color textText7 = Color(0xFF878593);
  static const Color textText8 = Color(0xFF853BCE);
  static const Color textText9 = Color(0xFFBF93EC);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
