// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://discord.com
// Generated: 2026-06-25T08:27:03.317Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#ffffff' | '#5865f2' | '#333333' | '#23272a' | '#1a2081' | '#35ed7e' | '#19175c' | '#5b62c7';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Ggsans' | 'Abcgintodiscord' | 'ABC Ginto Normal' | 'Times' | 'Abcgintodiscordnord';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '800';

export type SpacingToken = '1px' | '24px' | '29px' | '35px' | '48px' | '52px' | '56px' | '60px' | '64px' | '73px' | '76px' | '80px' | '96px' | '106px' | '125px' | '128px' | '134px' | '143px' | '154px' | '157px' | '160px' | '174px' | '185px' | '194px' | '197px' | '221px' | '235px' | '256px' | '293px' | '413px' | '426px' | '432px' | '445px';

export type RadiusToken = '12px' | '16px' | '40px' | '50px' | '60px' | '72px' | '88px';

export type DurationToken = '200ms' | '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
