// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://apple.com
// Generated: 2026-05-21T11:46:59.380Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#1d1d1f' | '#000000' | '#2997ff' | '#e8e8ed' | '#ffffff' | '#f5f5f7' | '#86868b' | '#0066cc' | '#0071e3' | '#6e6e73' | '#333336' | '#d2d2d7' | '#271a11' | '#ea33c0' | '#9fc6f4' | '#41626a' | '#3397d4' | '#371410';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'SF Pro Text' | 'SF Pro Display' | 'Arial';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '300' | '700';

export type SpacingToken = '1px' | '4px' | '24px' | '26px' | '29px' | '32px' | '34px' | '37px' | '40px' | '44px' | '48px' | '53px' | '56px' | '59px' | '80px' | '84px' | '88px' | '114px' | '128px';

export type RadiusToken = '5px' | '8px' | '11px' | '50px' | '980px' | '999px';

export type DurationToken = '20ms' | '100ms' | '160ms' | '300ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
