// Generated by designlang v7.0.0
// Source: https://loom.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF1868DB)
    val ActionSecondary = Color(0xFFFFAB00)
    val SurfaceDefault = Color(0xFFFFFFFF)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF1868DB)
    val BrandSecondary = Color(0xFFFFAB00)
    val NeutralN100 = Color(0xFF292A2E)
    val NeutralN200 = Color(0xFF000000)
    val NeutralN300 = Color(0xFFFFFFFF)
    val NeutralN400 = Color(0xFF696969)
    val NeutralN500 = Color(0xFF555555)
    val NeutralN600 = Color(0xFFF8F8F8)
    val NeutralN700 = Color(0xFF7D818A)
    val NeutralN800 = Color(0xFFD8D8D8)
    val NeutralN900 = Color(0xFFBBBBBB)
    val BackgroundBg0 = Color(0xFFFFFFFF)
    val BackgroundBg1 = Color(0xFF101214)
    val BackgroundBg2 = Color(0xFF1868DB)
    val BackgroundBg3 = Color(0xFFEED7FC)
    val BackgroundBg4 = Color(0xFFEFFFD6)
    val BackgroundBg5 = Color(0xFFF8EEFE)
    val BackgroundBg6 = Color(0xFFE9F2FE)
    val BackgroundBg7 = Color(0xFFFFF5D4)
    val BackgroundBg8 = Color(0xFF123263)
    val BackgroundBg9 = Color(0xFF1558BC)
    val BackgroundBg10 = Color(0xFF292A2E)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF292A2E)
    val TextText2 = Color(0xFF7D818A)
    val TextText3 = Color(0xFF101214)
    val TextText4 = Color(0xFFFFFFFF)
    val TextText5 = Color(0xFFFF613D)
    val TextText6 = Color(0xFF1868DB)
    val TextText7 = Color(0xFFBF63F3)
    val TextText8 = Color(0xFFC97CF4)
    val TextText9 = Color(0xFF48245D)
    val SpacingS0 = 1.dp
    val SpacingS1 = 15.dp
    val SpacingS2 = 23.dp
    val SpacingS3 = 30.dp
    val SpacingS4 = 35.dp
    val SpacingS5 = 40.dp
    val SpacingS6 = 48.dp
    val SpacingS7 = 56.dp
    val SpacingS8 = 64.dp
    val SpacingS9 = 80.dp
    val SpacingS10 = 84.dp
    val SpacingS11 = 103.dp
    val SpacingS12 = 154.dp
    val SpacingS13 = 192.dp
    val SpacingS14 = 269.dp
    val RadiusR0 = 1.dp
    val RadiusR1 = 6.dp
    val RadiusR2 = 12.dp
    val RadiusR3 = 16.dp
    val RadiusR4 = 24.dp
    val RadiusR5 = 39.dp
    val RadiusR6 = 50.dp
    val RadiusR7 = 66.dp
    val RadiusR8 = 9999.dp
}
