// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://spotify.com
// Generated: 2026-05-21T11:46:57.242Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#ffffff' | '#b3b3b3' | '#000000' | '#696969' | '#555555' | '#1ed760' | '#121212' | '#7c7c7c' | '#1f1f1f' | '#333333' | '#468254' | '#3860be' | '#346e4a' | '#292929' | '#0000ee' | '#c1c1c1' | '#002038' | '#eeeeee' | '#d8d8d8' | '#1db954' | '#b03830' | '#402830' | '#c03830' | '#701818' | '#817915' | '#384040' | '#186090' | '#93712d' | '#ba3cd1' | '#177ace' | '#687088' | '#318099' | '#cf4c1c' | '#7f7757' | '#e10096' | '#b02828' | '#883028' | '#067eb6' | '#517aa3' | '#418369' | '#284038' | '#381800' | '#c00808' | '#204090' | '#32ae88';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'SpotifyMixUI' | 'Times' | 'SpotifyMixUITitle';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '600' | '500';

export type SpacingToken = '1px' | '15px' | '20px' | '23px' | '28px' | '35px' | '40px' | '48px' | '64px' | '96px' | '125px' | '154px';

export type RadiusToken = '2px' | '6px' | '10px' | '16px' | '20px' | '32px' | '50px' | '500px' | '9999px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
