// Generated by designlang v7.0.0
// Source: https://mintlify.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFFAF8F5);
  static const Color actionSecondary = Color(0xFF004CFF);
  static const Color surfaceDefault = Color(0xFFF9F6F3);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 4;
  static const double spacingS1 = 40;
  static const double spacingS2 = 48;
  static const double spacingS3 = 64;
  static const double spacingS4 = 80;
  static const double spacingS5 = 93;
  static const double spacingS6 = 104;
  static const double spacingS7 = 128;
  static const double spacingS8 = 160;
  static const double spacingS9 = 266;
  static const double spacingS10 = 290;
  static const double spacingS11 = 298;
  static const double radiusR0 = 2;
  static const double radiusR1 = 6;
  static const double radiusR2 = 12;
  static const double radiusR3 = 24;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFFAF8F5);
  static const Color brandSecondary = Color(0xFF004CFF);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFF121715);
  static const Color neutralN400 = Color(0xFF969E9B);
  static const Color neutralN500 = Color(0xFF485450);
  static const Color neutralN600 = Color(0xFF717D79);
  static const Color neutralN700 = Color(0xFFCFCDCA);
  static const Color backgroundBg0 = Color(0xFFF9F6F3);
  static const Color backgroundBg1 = Color(0xFFEF6333);
  static const Color backgroundBg2 = Color(0xFF004CFF);
  static const Color backgroundBg3 = Color(0xFFFF7A59);
  static const Color backgroundBg4 = Color(0xFF00A8E0);
  static const Color backgroundBg5 = Color(0xFFFAF8F5);
  static const Color backgroundBg6 = Color(0xFFFEFDFB);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF0C8C5E);
  static const Color textText2 = Color(0xFF121715);
  static const Color textText3 = Color(0xFF717D79);
  static const Color textText4 = Color(0xFFFFFFFF);
  static const Color textText5 = Color(0xFF969E9B);
  static const Color textText6 = Color(0xFF485450);
  static const Color textText7 = Color(0xFFCFCDCA);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
