// Generated by designlang v7.0.0
// Source: https://posthog.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFE1D7C2);
  static const Color actionSecondary = Color(0xFFEB9D2A);
  static const Color surfaceDefault = Color(0xFFE5E7E0);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 20;
  static const double spacingS2 = 32;
  static const double spacingS3 = 48;
  static const double spacingS4 = 64;
  static const double spacingS5 = 120;
  static const double spacingS6 = 144;
  static const double spacingS7 = 220;
  static const double radiusR0 = 2;
  static const double radiusR1 = 5;
  static const double radiusR2 = 8;
  static const double radiusR3 = 9999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFE1D7C2);
  static const Color brandSecondary = Color(0xFFEB9D2A);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color neutralN200 = Color(0xFF4D4F46);
  static const Color neutralN300 = Color(0xFF374151);
  static const Color neutralN400 = Color(0xFF23251D);
  static const Color neutralN500 = Color(0xFF9EA096);
  static const Color neutralN600 = Color(0xFF65675E);
  static const Color neutralN700 = Color(0xFFBFC1B7);
  static const Color neutralN800 = Color(0xFFFFFFFF);
  static const Color neutralN900 = Color(0xFFB6B7AF);
  static const Color neutralN1000 = Color(0xFF131316);
  static const Color neutralN1100 = Color(0xFFD0D1C9);
  static const Color neutralN1200 = Color(0xFF73756B);
  static const Color backgroundBg0 = Color(0xFFE5E7E0);
  static const Color backgroundBg1 = Color(0xFFE1D7C2);
  static const Color backgroundBg2 = Color(0xFFFFFFFF);
  static const Color backgroundBg3 = Color(0xFFEEEFE9);
  static const Color backgroundBg4 = Color(0xFFFDFDF8);
  static const Color backgroundBg5 = Color(0xFF2F80FA);
  static const Color backgroundBg6 = Color(0xFFF3F4F0);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF23251D);
  static const Color textText2 = Color(0xFF73756B);
  static const Color textText3 = Color(0xFF65675E);
  static const Color textText4 = Color(0xFF4D4F46);
  static const Color textText5 = Color(0xFF9EA096);
  static const Color textText6 = Color(0xFF374151);
  static const Color textText7 = Color(0xFF111827);
  static const Color textText8 = Color(0xFFFFFFFF);
  static const Color textText9 = Color(0xFFB62AD9);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
