// Generated by designlang v7.0.0
// Source: https://coinbase.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF0000EE);
  static const Color textBody = Color(0xFF313131);
  static const double spacingS0 = 8;
  static const double spacingS1 = 128;
  static const double radiusR0 = 50;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF0000EE);
  static const Color neutralN100 = Color(0xFF313131);
  static const Color neutralN200 = Color(0xFF000000);
  static const Color neutralN300 = Color(0xFFD9D9D9);
  static const Color textText0 = Color(0xFF313131);
  static const Color textText1 = Color(0xFF000000);
  static const Color textText2 = Color(0xFF0000EE);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
    ),
  );
}
