// Generated by designlang v7.0.0
// Source: https://supabase.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF72E3AD);
  static const Color actionSecondary = Color(0xFF00BB68);
  static const Color surfaceDefault = Color(0xFFFCFCFC);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 40;
  static const double spacingS2 = 48;
  static const double spacingS3 = 64;
  static const double spacingS4 = 90;
  static const double spacingS5 = 112;
  static const double spacingS6 = 128;
  static const double spacingS7 = 157;
  static const double spacingS8 = 208;
  static const double spacingS9 = 246;
  static const double spacingS10 = 304;
  static const double radiusR0 = 6;
  static const double radiusR1 = 11;
  static const double radiusR2 = 16;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF72E3AD);
  static const Color brandSecondary = Color(0xFF00BB68);
  static const Color neutralN100 = Color(0xFFDFDFDF);
  static const Color neutralN200 = Color(0xFF171717);
  static const Color neutralN300 = Color(0xFF525252);
  static const Color neutralN400 = Color(0xFF707070);
  static const Color neutralN500 = Color(0xFFFFFFFF);
  static const Color neutralN600 = Color(0xFFB2B2B2);
  static const Color neutralN700 = Color(0xFF000000);
  static const Color neutralN800 = Color(0xFFC7C7C7);
  static const Color neutralN900 = Color(0xFFEDEDED);
  static const Color neutralN1000 = Color(0xFFD4D4D4);
  static const Color neutralN1100 = Color(0xFF292929);
  static const Color backgroundBg0 = Color(0xFFFCFCFC);
  static const Color backgroundBg1 = Color(0xFFF8F8F8);
  static const Color backgroundBg2 = Color(0xFFFFFFFF);
  static const Color backgroundBg3 = Color(0xFFFDFDFD);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF171717);
  static const Color textText2 = Color(0xFF525252);
  static const Color textText3 = Color(0xFF707070);
  static const Color textText4 = Color(0xFF3FCF8E);
  static const Color textText5 = Color(0xFFB2B2B2);
  static const Color textText6 = Color(0xFF00BB68);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
