// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://railway.app
// Generated: 2026-06-25T08:29:38.257Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#33323e' | '#f7f7f8' | '#545260' | '#13111c' | '#a1a0ab' | '#609f89' | '#c67839' | '#878593' | '#a667e4' | '#dcdce0' | '#3d2259' | '#59497a' | '#853bce' | '#42946e' | '#000000' | '#1b2132' | '#180d43' | '#1f132a' | '#291839' | '#bf93ec' | '#9c7016' | '#eab38a' | '#ed852f';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'JetBrains Mono' | 'Helvetica' | 'IBM Plex Serif';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700' | '800';

export type SpacingToken = '4px' | '60px' | '80px' | '96px' | '128px' | '159px' | '235px' | '262px';

export type RadiusToken = '4px' | '8px' | '16px' | '50px' | '9999px';

export type DurationToken = '50ms' | '100ms' | '200ms' | '400ms' | '700ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
