// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://posthog.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xE1D7C2)
  static let actionSecondary = Color(hex: 0xEB9D2A)
  static let surfaceDefault = Color(hex: 0xE5E7E0)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 20
  static let spacingS2: CGFloat = 32
  static let spacingS3: CGFloat = 48
  static let spacingS4: CGFloat = 64
  static let spacingS5: CGFloat = 120
  static let spacingS6: CGFloat = 144
  static let spacingS7: CGFloat = 220

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 2
  static let radiusR1: CGFloat = 5
  static let radiusR2: CGFloat = 8
  static let radiusR3: CGFloat = 9999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xE1D7C2)
  static let brandSecondary = Color(hex: 0xEB9D2A)
  static let neutralN100 = Color(hex: 0x000000)
  static let neutralN200 = Color(hex: 0x4D4F46)
  static let neutralN300 = Color(hex: 0x374151)
  static let neutralN400 = Color(hex: 0x23251D)
  static let neutralN500 = Color(hex: 0x9EA096)
  static let neutralN600 = Color(hex: 0x65675E)
  static let neutralN700 = Color(hex: 0xBFC1B7)
  static let neutralN800 = Color(hex: 0xFFFFFF)
  static let neutralN900 = Color(hex: 0xB6B7AF)
  static let neutralN1000 = Color(hex: 0x131316)
  static let neutralN1100 = Color(hex: 0xD0D1C9)
  static let neutralN1200 = Color(hex: 0x73756B)
  static let backgroundBg0 = Color(hex: 0xE5E7E0)
  static let backgroundBg1 = Color(hex: 0xE1D7C2)
  static let backgroundBg2 = Color(hex: 0xFFFFFF)
  static let backgroundBg3 = Color(hex: 0xEEEFE9)
  static let backgroundBg4 = Color(hex: 0xFDFDF8)
  static let backgroundBg5 = Color(hex: 0x2F80FA)
  static let backgroundBg6 = Color(hex: 0xF3F4F0)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x23251D)
  static let textText2 = Color(hex: 0x73756B)
  static let textText3 = Color(hex: 0x65675E)
  static let textText4 = Color(hex: 0x4D4F46)
  static let textText5 = Color(hex: 0x9EA096)
  static let textText6 = Color(hex: 0x374151)
  static let textText7 = Color(hex: 0x111827)
  static let textText8 = Color(hex: 0xFFFFFF)
  static let textText9 = Color(hex: 0xB62AD9)
}

// typography.body: family=IBM Plex Sans Variable size=36px weight=700 lineHeight=54px
