// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://v0.dev
// Generated: 2026-06-25T08:31:41.027Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = never;
export type ColorHex  = '#d2d2d2' | '#020202' | '#222222' | '#ffffff' | '#f4f4f4' | '#343434' | '#646464' | '#e2e2e2' | '#959595';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'GeistSans' | 'GeistMono' | 'Times';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600';

export type SpacingToken = '1px' | '64px' | '96px' | '108px' | '128px' | '192px' | '208px';

export type RadiusToken = '4px' | '8px' | '12px' | '16px' | '35px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
