// Generated by designlang v7.0.0
// Source: https://supabase.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF72E3AD)
    val ActionSecondary = Color(0xFF00BB68)
    val SurfaceDefault = Color(0xFFFCFCFC)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF72E3AD)
    val BrandSecondary = Color(0xFF00BB68)
    val NeutralN100 = Color(0xFFDFDFDF)
    val NeutralN200 = Color(0xFF171717)
    val NeutralN300 = Color(0xFF525252)
    val NeutralN400 = Color(0xFF707070)
    val NeutralN500 = Color(0xFFFFFFFF)
    val NeutralN600 = Color(0xFFB2B2B2)
    val NeutralN700 = Color(0xFF000000)
    val NeutralN800 = Color(0xFFC7C7C7)
    val NeutralN900 = Color(0xFFEDEDED)
    val NeutralN1000 = Color(0xFFD4D4D4)
    val NeutralN1100 = Color(0xFF292929)
    val BackgroundBg0 = Color(0xFFFCFCFC)
    val BackgroundBg1 = Color(0xFFF8F8F8)
    val BackgroundBg2 = Color(0xFFFFFFFF)
    val BackgroundBg3 = Color(0xFFFDFDFD)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF171717)
    val TextText2 = Color(0xFF525252)
    val TextText3 = Color(0xFF707070)
    val TextText4 = Color(0xFF3FCF8E)
    val TextText5 = Color(0xFFB2B2B2)
    val TextText6 = Color(0xFF00BB68)
    val SpacingS0 = 1.dp
    val SpacingS1 = 40.dp
    val SpacingS2 = 48.dp
    val SpacingS3 = 64.dp
    val SpacingS4 = 90.dp
    val SpacingS5 = 112.dp
    val SpacingS6 = 128.dp
    val SpacingS7 = 157.dp
    val SpacingS8 = 208.dp
    val SpacingS9 = 246.dp
    val SpacingS10 = 304.dp
    val RadiusR0 = 6.dp
    val RadiusR1 = 11.dp
    val RadiusR2 = 16.dp
}
