// Generated by designlang v7.0.0
// Source: https://clerk.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF6C47FF)
    val ActionSecondary = Color(0xFF1CC4FF)
    val SurfaceDefault = Color(0xFFF7F7F8)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFF6C47FF)
    val BrandSecondary = Color(0xFF1CC4FF)
    val NeutralN100 = Color(0xFFD9D9DE)
    val NeutralN200 = Color(0xFF000000)
    val NeutralN300 = Color(0xFFFFFFFF)
    val NeutralN400 = Color(0xFF131316)
    val NeutralN500 = Color(0xFF747686)
    val NeutralN600 = Color(0xFF5E5F6E)
    val NeutralN700 = Color(0xFF2F3037)
    val NeutralN800 = Color(0xFF9394A1)
    val NeutralN900 = Color(0xFF696A78)
    val NeutralN1000 = Color(0xFFEEEEF0)
    val NeutralN1100 = Color(0xFF212126)
    val NeutralN1200 = Color(0xFF42434D)
    val NeutralN1300 = Color(0xFFB7B8C2)
    val NeutralN1400 = Color(0xFF4A4C5B)
    val BackgroundBg0 = Color(0xFFF7F7F8)
    val BackgroundBg1 = Color(0xFFF8F8F8)
    val BackgroundBg2 = Color(0xFF131316)
    val BackgroundBg3 = Color(0xFFFFFFFF)
    val BackgroundBg4 = Color(0xFF212126)
    val BackgroundBg5 = Color(0xFF2D2E3D)
    val BackgroundBg6 = Color(0xFF29292E)
    val BackgroundBg7 = Color(0xFF25252A)
    val BackgroundBg8 = Color(0xFF2F3037)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFFFFFFFF)
    val TextText2 = Color(0xFF131316)
    val TextText3 = Color(0xFF747686)
    val TextText4 = Color(0xFF5E5F6E)
    val TextText5 = Color(0xFF212126)
    val TextText6 = Color(0xFF6C47FF)
    val TextText7 = Color(0xFF9394A1)
    val TextText8 = Color(0xFF696A78)
    val TextText9 = Color(0xFF42434D)
    val SpacingS0 = 1.dp
    val SpacingS1 = 46.dp
    val SpacingS2 = 56.dp
    val SpacingS3 = 76.dp
    val SpacingS4 = 94.dp
    val SpacingS5 = 128.dp
    val SpacingS6 = 140.dp
    val SpacingS7 = 151.dp
    val SpacingS8 = 158.dp
    val SpacingS9 = 167.dp
    val SpacingS10 = 172.dp
    val SpacingS11 = 192.dp
    val SpacingS12 = 220.dp
    val SpacingS13 = 259.dp
    val SpacingS14 = 272.dp
    val SpacingS15 = 302.dp
    val SpacingS16 = 320.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 5.dp
    val RadiusR2 = 8.dp
    val RadiusR3 = 12.dp
    val RadiusR4 = 16.dp
    val RadiusR5 = 38.dp
    val RadiusR6 = 44.dp
    val RadiusR7 = 50.dp
}
