// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://loom.com
// Generated: 2026-06-25T08:28:20.983Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#292a2e' | '#101214' | '#000000' | '#ffffff' | '#1868db' | '#696969' | '#e9f2fe' | '#555555' | '#bf63f3' | '#3860be' | '#ff613d' | '#ffab00' | '#27455c' | '#f8f8f8' | '#48245d' | '#172b4d' | '#82b536' | '#7d818a' | '#c97cf4' | '#123263' | '#1558bc' | '#0052cc' | '#d8d8d8' | '#eed7fc' | '#efffd6' | '#fff5d4' | '#32ae88' | '#bbbbbb';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Charlie Text' | 'Charlie Display' | 'Times';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '500' | '600';

export type SpacingToken = '1px' | '15px' | '23px' | '30px' | '35px' | '40px' | '48px' | '56px' | '64px' | '80px' | '84px' | '103px' | '154px' | '192px' | '269px';

export type RadiusToken = '1px' | '6px' | '12px' | '16px' | '24px' | '39px' | '50px' | '66px' | '9999px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
