// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://coinbase.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x0000EE)
  static let textBody = Color(hex: 0x313131)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 8
  static let spacingS1: CGFloat = 128

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 50
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x0000EE)
  static let neutralN100 = Color(hex: 0x313131)
  static let neutralN200 = Color(hex: 0x000000)
  static let neutralN300 = Color(hex: 0xD9D9D9)
  static let textText0 = Color(hex: 0x313131)
  static let textText1 = Color(hex: 0x000000)
  static let textText2 = Color(hex: 0x0000EE)
}

// typography.body: family=Arial size=40px weight=600 lineHeight=50px
