// Generated by designlang v7.0.0
// Source: https://railway.app
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF59497A)
    val ActionSecondary = Color(0xFF291839)
    val SurfaceDefault = Color(0xFF13111C)
    val TextBody = Color(0xFFFFFFFF)
    val BrandPrimary = Color(0xFF59497A)
    val BrandSecondary = Color(0xFF291839)
    val NeutralN100 = Color(0xFF33323E)
    val NeutralN200 = Color(0xFFF7F7F8)
    val NeutralN300 = Color(0xFF545260)
    val NeutralN400 = Color(0xFFA1A0AB)
    val NeutralN500 = Color(0xFF609F89)
    val NeutralN600 = Color(0xFF878593)
    val NeutralN700 = Color(0xFFDCDCE0)
    val NeutralN800 = Color(0xFF000000)
    val BackgroundBg0 = Color(0xFF13111C)
    val BackgroundBg1 = Color(0xFF000000)
    val BackgroundBg2 = Color(0xFF180D43)
    val BackgroundBg3 = Color(0xFF1F132A)
    val BackgroundBg4 = Color(0xFF0D0C14)
    val BackgroundBg5 = Color(0xFF1B2132)
    val BackgroundBg6 = Color(0xFF1F2B2E)
    val TextText0 = Color(0xFFFFFFFF)
    val TextText1 = Color(0xFF13111C)
    val TextText2 = Color(0xFFA667E4)
    val TextText3 = Color(0xFFF7F7F8)
    val TextText4 = Color(0xFFDCDCE0)
    val TextText5 = Color(0xFFA1A0AB)
    val TextText6 = Color(0xFF545260)
    val TextText7 = Color(0xFF878593)
    val TextText8 = Color(0xFF853BCE)
    val TextText9 = Color(0xFFBF93EC)
    val SpacingS0 = 4.dp
    val SpacingS1 = 60.dp
    val SpacingS2 = 80.dp
    val SpacingS3 = 96.dp
    val SpacingS4 = 128.dp
    val SpacingS5 = 159.dp
    val SpacingS6 = 235.dp
    val SpacingS7 = 262.dp
    val RadiusR0 = 4.dp
    val RadiusR1 = 8.dp
    val RadiusR2 = 16.dp
    val RadiusR3 = 50.dp
    val RadiusR4 = 9999.dp
}
