// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://retool.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xE9EBDF)
  static let actionSecondary = Color(hex: 0x518DD2)
  static let surfaceDefault = Color(hex: 0x151515)
  static let textBody = Color(hex: 0xFFFFFF)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 20
  static let spacingS2: CGFloat = 24
  static let spacingS3: CGFloat = 28
  static let spacingS4: CGFloat = 32
  static let spacingS5: CGFloat = 40
  static let spacingS6: CGFloat = 56
  static let spacingS7: CGFloat = 64
  static let spacingS8: CGFloat = 71
  static let spacingS9: CGFloat = 80
  static let spacingS10: CGFloat = 120
  static let spacingS11: CGFloat = 158
  static let spacingS12: CGFloat = 384

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 4
  static let radiusR1: CGFloat = 8
  static let radiusR2: CGFloat = 12
  static let radiusR3: CGFloat = 16
  static let radiusR4: CGFloat = 20
  static let radiusR5: CGFloat = 24
  static let radiusR6: CGFloat = 36
  static let radiusR7: CGFloat = 50
  static let radiusR8: CGFloat = 9999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xE9EBDF)
  static let brandSecondary = Color(hex: 0x518DD2)
  static let neutralN100 = Color(hex: 0x151515)
  static let neutralN200 = Color(hex: 0xFFFFFF)
  static let neutralN300 = Color(hex: 0xCBCCC4)
  static let neutralN400 = Color(hex: 0x242424)
  static let neutralN500 = Color(hex: 0x8B867F)
  static let neutralN600 = Color(hex: 0xB6B8AF)
  static let neutralN700 = Color(hex: 0x000000)
  static let neutralN800 = Color(hex: 0xD9D9D9)
  static let neutralN900 = Color(hex: 0x433E38)
  static let backgroundBg0 = Color(hex: 0x151515)
  static let backgroundBg1 = Color(hex: 0x000000)
  static let backgroundBg2 = Color(hex: 0xE9EBDF)
  static let backgroundBg3 = Color(hex: 0x242424)
  static let textText0 = Color(hex: 0xFFFFFF)
  static let textText1 = Color(hex: 0xE9EBDF)
  static let textText2 = Color(hex: 0x151515)
  static let textText3 = Color(hex: 0xF7F8F4)
  static let textText4 = Color(hex: 0xCBCCC4)
  static let textText5 = Color(hex: 0x242424)
  static let textText6 = Color(hex: 0x8B867F)
  static let textText7 = Color(hex: 0xB6B8AF)
}

// typography.body: family=saansFont size=68.9231px weight=300 lineHeight=72.3693px
