// Generated by designlang v7.0.0
// Source: https://perplexity.ai
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF0000EE)
    val TextBody = Color(0xFF313131)
    val BrandPrimary = Color(0xFF0000EE)
    val NeutralN100 = Color(0xFF313131)
    val NeutralN200 = Color(0xFF000000)
    val NeutralN300 = Color(0xFFD9D9D9)
    val TextText0 = Color(0xFF313131)
    val TextText1 = Color(0xFF000000)
    val TextText2 = Color(0xFF0000EE)
    val SpacingS0 = 8.dp
    val SpacingS1 = 128.dp
    val RadiusR0 = 50.dp
}
