// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://postman.com
// Generated: 2026-06-25T08:29:28.872Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#212121' | '#000000' | '#707070' | '#ffffff' | '#0265d2' | '#5c5c5c' | '#e05320' | '#e6e6e6' | '#09070d' | '#140b1e' | '#007bff' | '#8a8a8a' | '#cfcfcf' | '#ff6c37' | '#b387f5';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'inter' | 'ibmPlexMono' | 'degular' | 'Times';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600';

export type SpacingToken = '1px' | '20px' | '24px' | '40px' | '50px' | '60px' | '64px' | '80px' | '120px' | '224px' | '252px';

export type RadiusToken = '3px' | '10px' | '15px' | '20px' | '9999px';

export type DurationToken = '100ms' | '200ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
