// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://raycast.com
// Generated: 2026-06-25T08:25:22.097Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#ffffff' | '#6a6b6c' | '#9c9c9d' | '#434345' | '#e6e6e6' | '#2f3031' | '#08090c' | '#1b1c1e' | '#452324' | '#ff6363' | '#8e8c90' | '#9ebed7' | '#8cd6ff' | '#59d499' | '#56c2ff' | '#ffc531' | '#111214' | '#d72a2a';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'SF Pro Text' | 'SF Pro' | 'GeistMono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700' | '600' | '300';

export type SpacingToken = '1px' | '45px' | '56px' | '64px' | '72px' | '80px' | '96px' | '102px' | '120px' | '128px' | '137px' | '148px' | '169px' | '200px' | '212px' | '217px' | '224px' | '325px' | '370px' | '400px' | '409px' | '416px';

export type RadiusToken = '2px' | '5px' | '8px' | '11px' | '16px' | '19px' | '22px' | '31px' | '36px' | '43px' | '86px' | '100px' | '1000px' | '99999px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms' | '850ms' | '1500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
