// Generated by designlang v7.0.0
// Source: https://retool.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFE9EBDF)
    val ActionSecondary = Color(0xFF518DD2)
    val SurfaceDefault = Color(0xFF151515)
    val TextBody = Color(0xFFFFFFFF)
    val BrandPrimary = Color(0xFFE9EBDF)
    val BrandSecondary = Color(0xFF518DD2)
    val NeutralN100 = Color(0xFF151515)
    val NeutralN200 = Color(0xFFFFFFFF)
    val NeutralN300 = Color(0xFFCBCCC4)
    val NeutralN400 = Color(0xFF242424)
    val NeutralN500 = Color(0xFF8B867F)
    val NeutralN600 = Color(0xFFB6B8AF)
    val NeutralN700 = Color(0xFF000000)
    val NeutralN800 = Color(0xFFD9D9D9)
    val NeutralN900 = Color(0xFF433E38)
    val BackgroundBg0 = Color(0xFF151515)
    val BackgroundBg1 = Color(0xFF000000)
    val BackgroundBg2 = Color(0xFFE9EBDF)
    val BackgroundBg3 = Color(0xFF242424)
    val TextText0 = Color(0xFFFFFFFF)
    val TextText1 = Color(0xFFE9EBDF)
    val TextText2 = Color(0xFF151515)
    val TextText3 = Color(0xFFF7F8F4)
    val TextText4 = Color(0xFFCBCCC4)
    val TextText5 = Color(0xFF242424)
    val TextText6 = Color(0xFF8B867F)
    val TextText7 = Color(0xFFB6B8AF)
    val SpacingS0 = 1.dp
    val SpacingS1 = 20.dp
    val SpacingS2 = 24.dp
    val SpacingS3 = 28.dp
    val SpacingS4 = 32.dp
    val SpacingS5 = 40.dp
    val SpacingS6 = 56.dp
    val SpacingS7 = 64.dp
    val SpacingS8 = 71.dp
    val SpacingS9 = 80.dp
    val SpacingS10 = 120.dp
    val SpacingS11 = 158.dp
    val SpacingS12 = 384.dp
    val RadiusR0 = 4.dp
    val RadiusR1 = 8.dp
    val RadiusR2 = 12.dp
    val RadiusR3 = 16.dp
    val RadiusR4 = 20.dp
    val RadiusR5 = 24.dp
    val RadiusR6 = 36.dp
    val RadiusR7 = 50.dp
    val RadiusR8 = 9999.dp
}
