// Generated by designlang v7.0.0
// Source: https://framer.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF0066FF);
  static const Color actionSecondary = Color(0xFF0000EE);
  static const Color surfaceDefault = Color(0xFF000000);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 20;
  static const double spacingS2 = 25;
  static const double spacingS3 = 30;
  static const double spacingS4 = 40;
  static const double spacingS5 = 45;
  static const double spacingS6 = 50;
  static const double spacingS7 = 55;
  static const double spacingS8 = 60;
  static const double spacingS9 = 64;
  static const double spacingS10 = 100;
  static const double spacingS11 = 120;
  static const double spacingS12 = 160;
  static const double spacingS13 = 200;
  static const double radiusR0 = 1;
  static const double radiusR1 = 4;
  static const double radiusR2 = 7;
  static const double radiusR3 = 10;
  static const double radiusR4 = 14;
  static const double radiusR5 = 18;
  static const double radiusR6 = 21;
  static const double radiusR7 = 25;
  static const double radiusR8 = 30;
  static const double radiusR9 = 50;
  static const double radiusR10 = 100;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF0066FF);
  static const Color brandSecondary = Color(0xFF0000EE);
  static const Color neutralN100 = Color(0xFF000000);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFF999999);
  static const Color neutralN400 = Color(0xFF242424);
  static const Color neutralN500 = Color(0xFF666666);
  static const Color neutralN600 = Color(0xFF111111);
  static const Color neutralN700 = Color(0xFFCCCCCC);
  static const Color neutralN800 = Color(0xFF303030);
  static const Color neutralN900 = Color(0xFF878787);
  static const Color neutralN1000 = Color(0xFF444444);
  static const Color neutralN1100 = Color(0xFF1A1A1A);
  static const Color neutralN1200 = Color(0xFFEEEEEE);
  static const Color backgroundBg0 = Color(0xFF000000);
  static const Color backgroundBg1 = Color(0xFF111111);
  static const Color backgroundBg2 = Color(0xFF171717);
  static const Color backgroundBg3 = Color(0xFF0099FF);
  static const Color backgroundBg4 = Color(0xFFFFFFFF);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF0000EE);
  static const Color textText2 = Color(0xFFFFFFFF);
  static const Color textText3 = Color(0xFF999999);
  static const Color textText4 = Color(0xFF9A9997);
  static const Color textText5 = Color(0xFF666666);
  static const Color textText6 = Color(0xFF444444);
  static const Color textText7 = Color(0xFFCCCCCC);
  static const Color textText8 = Color(0xFF0099FF);
  static const Color textText9 = Color(0xFF00BB88);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
