// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://v0.dev
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0xD2D2D2)
  static let surfaceDefault = Color(hex: 0xF4F4F4)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 64
  static let spacingS2: CGFloat = 96
  static let spacingS3: CGFloat = 108
  static let spacingS4: CGFloat = 128
  static let spacingS5: CGFloat = 192
  static let spacingS6: CGFloat = 208

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 4
  static let radiusR1: CGFloat = 8
  static let radiusR2: CGFloat = 12
  static let radiusR3: CGFloat = 16
  static let radiusR4: CGFloat = 35
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0xD2D2D2)
  static let neutralN100 = Color(hex: 0xD2D2D2)
  static let neutralN200 = Color(hex: 0x020202)
  static let neutralN300 = Color(hex: 0x222222)
  static let neutralN400 = Color(hex: 0xFFFFFF)
  static let neutralN500 = Color(hex: 0xF4F4F4)
  static let neutralN600 = Color(hex: 0x343434)
  static let neutralN700 = Color(hex: 0x646464)
  static let neutralN800 = Color(hex: 0xE2E2E2)
  static let neutralN900 = Color(hex: 0x959595)
  static let backgroundBg0 = Color(hex: 0xF4F4F4)
  static let backgroundBg1 = Color(hex: 0xFFFFFF)
  static let backgroundBg2 = Color(hex: 0xE2E2E2)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x020202)
  static let textText2 = Color(hex: 0x222222)
  static let textText3 = Color(hex: 0xFFFFFF)
  static let textText4 = Color(hex: 0x646464)
  static let textText5 = Color(hex: 0x343434)
}

// typography.body: family=GeistSans size=48px weight=600 lineHeight=56px
