// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://linear.app
// Generated: 2026-05-21T11:46:56.718Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#f7f8f8' | '#62666d' | '#d0d6e0' | '#e2e4e7' | '#8a8f98' | '#f79ce0' | '#08090a' | '#f7bf8b' | '#8fa6ff' | '#ffdf9f' | '#83dcdc' | '#00ff05' | '#23252a' | '#f34e52' | '#27a644' | '#383b3f' | '#000000' | '#ff0000' | '#6366f1' | '#02b8cc' | '#5e6ad2' | '#121414' | '#8b5cf6' | '#55ccff' | '#6d78d5' | '#e4f222' | '#10b981' | '#0f3338' | '#422222' | '#1c85e8';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter Variable' | 'Berkeley Mono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '510' | '590' | '300';

export type SpacingToken = '1px' | '39px' | '47px' | '51px' | '56px' | '69px' | '79px' | '91px' | '95px' | '99px' | '111px' | '123px' | '127px' | '131px' | '135px' | '152px' | '155px' | '159px' | '166px' | '199px' | '203px' | '212px' | '216px' | '220px' | '224px' | '282px' | '375px' | '385px' | '450px';

export type RadiusToken = '1px' | '4px' | '7px' | '12px' | '16px' | '20px' | '50px' | '400px' | '9999px';

export type DurationToken = '100ms' | '160ms' | '400ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
