// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://loom.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x1868DB)
  static let actionSecondary = Color(hex: 0xFFAB00)
  static let surfaceDefault = Color(hex: 0xFFFFFF)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 15
  static let spacingS2: CGFloat = 23
  static let spacingS3: CGFloat = 30
  static let spacingS4: CGFloat = 35
  static let spacingS5: CGFloat = 40
  static let spacingS6: CGFloat = 48
  static let spacingS7: CGFloat = 56
  static let spacingS8: CGFloat = 64
  static let spacingS9: CGFloat = 80
  static let spacingS10: CGFloat = 84
  static let spacingS11: CGFloat = 103
  static let spacingS12: CGFloat = 154
  static let spacingS13: CGFloat = 192
  static let spacingS14: CGFloat = 269

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 1
  static let radiusR1: CGFloat = 6
  static let radiusR2: CGFloat = 12
  static let radiusR3: CGFloat = 16
  static let radiusR4: CGFloat = 24
  static let radiusR5: CGFloat = 39
  static let radiusR6: CGFloat = 50
  static let radiusR7: CGFloat = 66
  static let radiusR8: CGFloat = 9999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x1868DB)
  static let brandSecondary = Color(hex: 0xFFAB00)
  static let neutralN100 = Color(hex: 0x292A2E)
  static let neutralN200 = Color(hex: 0x000000)
  static let neutralN300 = Color(hex: 0xFFFFFF)
  static let neutralN400 = Color(hex: 0x696969)
  static let neutralN500 = Color(hex: 0x555555)
  static let neutralN600 = Color(hex: 0xF8F8F8)
  static let neutralN700 = Color(hex: 0x7D818A)
  static let neutralN800 = Color(hex: 0xD8D8D8)
  static let neutralN900 = Color(hex: 0xBBBBBB)
  static let backgroundBg0 = Color(hex: 0xFFFFFF)
  static let backgroundBg1 = Color(hex: 0x101214)
  static let backgroundBg2 = Color(hex: 0x1868DB)
  static let backgroundBg3 = Color(hex: 0xEED7FC)
  static let backgroundBg4 = Color(hex: 0xEFFFD6)
  static let backgroundBg5 = Color(hex: 0xF8EEFE)
  static let backgroundBg6 = Color(hex: 0xE9F2FE)
  static let backgroundBg7 = Color(hex: 0xFFF5D4)
  static let backgroundBg8 = Color(hex: 0x123263)
  static let backgroundBg9 = Color(hex: 0x1558BC)
  static let backgroundBg10 = Color(hex: 0x292A2E)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x292A2E)
  static let textText2 = Color(hex: 0x7D818A)
  static let textText3 = Color(hex: 0x101214)
  static let textText4 = Color(hex: 0xFFFFFF)
  static let textText5 = Color(hex: 0xFF613D)
  static let textText6 = Color(hex: 0x1868DB)
  static let textText7 = Color(hex: 0xBF63F3)
  static let textText8 = Color(hex: 0xC97CF4)
  static let textText9 = Color(hex: 0x48245D)
}

// typography.body: family=Charlie Text size=56.5385px weight=700 lineHeight=58.1781px
