// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://framer.com
// Generated: 2026-06-25T08:25:38.709Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#ffffff' | '#999999' | '#242424' | '#0099ff' | '#666666' | '#111111' | '#00bb88' | '#cccccc' | '#303030' | '#d67a5c' | '#9869fd' | '#4cd963' | '#878787' | '#444444' | '#8856ff' | '#3a92fd' | '#ff0022' | '#ffbb00' | '#0066ff' | '#1a1a1a' | '#eeeeee';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Inter' | 'Inter Variable' | 'Times' | 'Input Mono Regular' | 'GT Walsheim Medium' | 'Input Mono Bold' | 'Inter Medium' | 'JetBrains Mono' | 'Inter Framer Regular' | 'Inter Framer SemiBold';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '700';

export type SpacingToken = '1px' | '20px' | '25px' | '30px' | '40px' | '45px' | '50px' | '55px' | '60px' | '64px' | '100px' | '120px' | '160px' | '200px';

export type RadiusToken = '1px' | '4px' | '7px' | '10px' | '14px' | '18px' | '21px' | '25px' | '30px' | '50px' | '100px';

export type DurationToken = '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
