// Generated by designlang v7.0.0
// Source: https://mintlify.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFFAF8F5)
    val ActionSecondary = Color(0xFF004CFF)
    val SurfaceDefault = Color(0xFFF9F6F3)
    val TextBody = Color(0xFF000000)
    val BrandPrimary = Color(0xFFFAF8F5)
    val BrandSecondary = Color(0xFF004CFF)
    val NeutralN100 = Color(0xFF000000)
    val NeutralN200 = Color(0xFFFFFFFF)
    val NeutralN300 = Color(0xFF121715)
    val NeutralN400 = Color(0xFF969E9B)
    val NeutralN500 = Color(0xFF485450)
    val NeutralN600 = Color(0xFF717D79)
    val NeutralN700 = Color(0xFFCFCDCA)
    val BackgroundBg0 = Color(0xFFF9F6F3)
    val BackgroundBg1 = Color(0xFFEF6333)
    val BackgroundBg2 = Color(0xFF004CFF)
    val BackgroundBg3 = Color(0xFFFF7A59)
    val BackgroundBg4 = Color(0xFF00A8E0)
    val BackgroundBg5 = Color(0xFFFAF8F5)
    val BackgroundBg6 = Color(0xFFFEFDFB)
    val TextText0 = Color(0xFF000000)
    val TextText1 = Color(0xFF0C8C5E)
    val TextText2 = Color(0xFF121715)
    val TextText3 = Color(0xFF717D79)
    val TextText4 = Color(0xFFFFFFFF)
    val TextText5 = Color(0xFF969E9B)
    val TextText6 = Color(0xFF485450)
    val TextText7 = Color(0xFFCFCDCA)
    val SpacingS0 = 4.dp
    val SpacingS1 = 40.dp
    val SpacingS2 = 48.dp
    val SpacingS3 = 64.dp
    val SpacingS4 = 80.dp
    val SpacingS5 = 93.dp
    val SpacingS6 = 104.dp
    val SpacingS7 = 128.dp
    val SpacingS8 = 160.dp
    val SpacingS9 = 266.dp
    val SpacingS10 = 290.dp
    val SpacingS11 = 298.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 6.dp
    val RadiusR2 = 12.dp
    val RadiusR3 = 24.dp
}
