// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://railway.app
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x59497A)
  static let actionSecondary = Color(hex: 0x291839)
  static let surfaceDefault = Color(hex: 0x13111C)
  static let textBody = Color(hex: 0xFFFFFF)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 4
  static let spacingS1: CGFloat = 60
  static let spacingS2: CGFloat = 80
  static let spacingS3: CGFloat = 96
  static let spacingS4: CGFloat = 128
  static let spacingS5: CGFloat = 159
  static let spacingS6: CGFloat = 235
  static let spacingS7: CGFloat = 262

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 4
  static let radiusR1: CGFloat = 8
  static let radiusR2: CGFloat = 16
  static let radiusR3: CGFloat = 50
  static let radiusR4: CGFloat = 9999
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x59497A)
  static let brandSecondary = Color(hex: 0x291839)
  static let neutralN100 = Color(hex: 0x33323E)
  static let neutralN200 = Color(hex: 0xF7F7F8)
  static let neutralN300 = Color(hex: 0x545260)
  static let neutralN400 = Color(hex: 0xA1A0AB)
  static let neutralN500 = Color(hex: 0x609F89)
  static let neutralN600 = Color(hex: 0x878593)
  static let neutralN700 = Color(hex: 0xDCDCE0)
  static let neutralN800 = Color(hex: 0x000000)
  static let backgroundBg0 = Color(hex: 0x13111C)
  static let backgroundBg1 = Color(hex: 0x000000)
  static let backgroundBg2 = Color(hex: 0x180D43)
  static let backgroundBg3 = Color(hex: 0x1F132A)
  static let backgroundBg4 = Color(hex: 0x0D0C14)
  static let backgroundBg5 = Color(hex: 0x1B2132)
  static let backgroundBg6 = Color(hex: 0x1F2B2E)
  static let textText0 = Color(hex: 0xFFFFFF)
  static let textText1 = Color(hex: 0x13111C)
  static let textText2 = Color(hex: 0xA667E4)
  static let textText3 = Color(hex: 0xF7F7F8)
  static let textText4 = Color(hex: 0xDCDCE0)
  static let textText5 = Color(hex: 0xA1A0AB)
  static let textText6 = Color(hex: 0x545260)
  static let textText7 = Color(hex: 0x878593)
  static let textText8 = Color(hex: 0x853BCE)
  static let textText9 = Color(hex: 0xBF93EC)
}

// typography.body: family=Inter size=54px weight=500 lineHeight=60.48px
