// Generated by designlang v7.0.0
// Source: https://retool.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFE9EBDF);
  static const Color actionSecondary = Color(0xFF518DD2);
  static const Color surfaceDefault = Color(0xFF151515);
  static const Color textBody = Color(0xFFFFFFFF);
  static const double spacingS0 = 1;
  static const double spacingS1 = 20;
  static const double spacingS2 = 24;
  static const double spacingS3 = 28;
  static const double spacingS4 = 32;
  static const double spacingS5 = 40;
  static const double spacingS6 = 56;
  static const double spacingS7 = 64;
  static const double spacingS8 = 71;
  static const double spacingS9 = 80;
  static const double spacingS10 = 120;
  static const double spacingS11 = 158;
  static const double spacingS12 = 384;
  static const double radiusR0 = 4;
  static const double radiusR1 = 8;
  static const double radiusR2 = 12;
  static const double radiusR3 = 16;
  static const double radiusR4 = 20;
  static const double radiusR5 = 24;
  static const double radiusR6 = 36;
  static const double radiusR7 = 50;
  static const double radiusR8 = 9999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFE9EBDF);
  static const Color brandSecondary = Color(0xFF518DD2);
  static const Color neutralN100 = Color(0xFF151515);
  static const Color neutralN200 = Color(0xFFFFFFFF);
  static const Color neutralN300 = Color(0xFFCBCCC4);
  static const Color neutralN400 = Color(0xFF242424);
  static const Color neutralN500 = Color(0xFF8B867F);
  static const Color neutralN600 = Color(0xFFB6B8AF);
  static const Color neutralN700 = Color(0xFF000000);
  static const Color neutralN800 = Color(0xFFD9D9D9);
  static const Color neutralN900 = Color(0xFF433E38);
  static const Color backgroundBg0 = Color(0xFF151515);
  static const Color backgroundBg1 = Color(0xFF000000);
  static const Color backgroundBg2 = Color(0xFFE9EBDF);
  static const Color backgroundBg3 = Color(0xFF242424);
  static const Color textText0 = Color(0xFFFFFFFF);
  static const Color textText1 = Color(0xFFE9EBDF);
  static const Color textText2 = Color(0xFF151515);
  static const Color textText3 = Color(0xFFF7F8F4);
  static const Color textText4 = Color(0xFFCBCCC4);
  static const Color textText5 = Color(0xFF242424);
  static const Color textText6 = Color(0xFF8B867F);
  static const Color textText7 = Color(0xFFB6B8AF);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
