// Generated by designlang v7.0.0
// Source: https://postman.com
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFFE05320);
  static const Color actionSecondary = Color(0xFF007BFF);
  static const Color surfaceDefault = Color(0xFFFFFFFF);
  static const Color textBody = Color(0xFF000000);
  static const double spacingS0 = 1;
  static const double spacingS1 = 20;
  static const double spacingS2 = 24;
  static const double spacingS3 = 40;
  static const double spacingS4 = 50;
  static const double spacingS5 = 60;
  static const double spacingS6 = 64;
  static const double spacingS7 = 80;
  static const double spacingS8 = 120;
  static const double spacingS9 = 224;
  static const double spacingS10 = 252;
  static const double radiusR0 = 3;
  static const double radiusR1 = 10;
  static const double radiusR2 = 15;
  static const double radiusR3 = 20;
  static const double radiusR4 = 9999;

  // Primitive palette
  static const Color brandPrimary = Color(0xFFE05320);
  static const Color brandSecondary = Color(0xFF007BFF);
  static const Color neutralN100 = Color(0xFF212121);
  static const Color neutralN200 = Color(0xFF000000);
  static const Color neutralN300 = Color(0xFF707070);
  static const Color neutralN400 = Color(0xFFFFFFFF);
  static const Color neutralN500 = Color(0xFF5C5C5C);
  static const Color neutralN600 = Color(0xFFE6E6E6);
  static const Color neutralN700 = Color(0xFF09070D);
  static const Color neutralN800 = Color(0xFF8A8A8A);
  static const Color neutralN900 = Color(0xFFCFCFCF);
  static const Color backgroundBg0 = Color(0xFFFFFFFF);
  static const Color backgroundBg1 = Color(0xFFF9F8F7);
  static const Color backgroundBg2 = Color(0xFFFF6C37);
  static const Color backgroundBg3 = Color(0xFF140B1E);
  static const Color backgroundBg4 = Color(0xFF09070D);
  static const Color textText0 = Color(0xFF000000);
  static const Color textText1 = Color(0xFF212121);
  static const Color textText2 = Color(0xFF0265D2);
  static const Color textText3 = Color(0xFF6B6B6B);
  static const Color textText4 = Color(0xFFE05320);
  static const Color textText5 = Color(0xFF5C5C5C);
  static const Color textText6 = Color(0xFFFFFFFF);
  static const Color textText7 = Color(0xFF707070);
  static const Color textText8 = Color(0xFF007BFF);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
