// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://discord.com
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x5865F2)
  static let actionSecondary = Color(hex: 0x35ED7E)
  static let surfaceDefault = Color(hex: 0x1A2081)
  static let textBody = Color(hex: 0x000000)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 1
  static let spacingS1: CGFloat = 24
  static let spacingS2: CGFloat = 29
  static let spacingS3: CGFloat = 35
  static let spacingS4: CGFloat = 48
  static let spacingS5: CGFloat = 52
  static let spacingS6: CGFloat = 56
  static let spacingS7: CGFloat = 60
  static let spacingS8: CGFloat = 64
  static let spacingS9: CGFloat = 73
  static let spacingS10: CGFloat = 76
  static let spacingS11: CGFloat = 80
  static let spacingS12: CGFloat = 96
  static let spacingS13: CGFloat = 106
  static let spacingS14: CGFloat = 125
  static let spacingS15: CGFloat = 128
  static let spacingS16: CGFloat = 134
  static let spacingS17: CGFloat = 143
  static let spacingS18: CGFloat = 154
  static let spacingS19: CGFloat = 157
  static let spacingS20: CGFloat = 160
  static let spacingS21: CGFloat = 174
  static let spacingS22: CGFloat = 185
  static let spacingS23: CGFloat = 194
  static let spacingS24: CGFloat = 197
  static let spacingS25: CGFloat = 221
  static let spacingS26: CGFloat = 235
  static let spacingS27: CGFloat = 256
  static let spacingS28: CGFloat = 293
  static let spacingS29: CGFloat = 413
  static let spacingS30: CGFloat = 426
  static let spacingS31: CGFloat = 432
  static let spacingS32: CGFloat = 445

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 12
  static let radiusR1: CGFloat = 16
  static let radiusR2: CGFloat = 40
  static let radiusR3: CGFloat = 50
  static let radiusR4: CGFloat = 60
  static let radiusR5: CGFloat = 72
  static let radiusR6: CGFloat = 88
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x5865F2)
  static let brandSecondary = Color(hex: 0x35ED7E)
  static let neutralN100 = Color(hex: 0x000000)
  static let neutralN200 = Color(hex: 0xFFFFFF)
  static let neutralN300 = Color(hex: 0x333333)
  static let neutralN400 = Color(hex: 0x23272A)
  static let backgroundBg0 = Color(hex: 0x1A2081)
  static let backgroundBg1 = Color(hex: 0x000000)
  static let textText0 = Color(hex: 0x000000)
  static let textText1 = Color(hex: 0x333333)
  static let textText2 = Color(hex: 0xFFFFFF)
  static let textText3 = Color(hex: 0x23272A)
  static let textText4 = Color(hex: 0x5865F2)
}

// typography.body: family=Ggsans size=61px weight=700 lineHeight=25px
