// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://netflix.com
// Generated: 2026-06-25T08:24:57.435Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#ffffff' | '#000000' | '#333333' | '#232323' | '#414141' | '#555555' | '#e50914' | '#3860be' | '#f4f4f4' | '#161616' | '#808080' | '#c1c1c1' | '#468254' | '#32ae88' | '#707070' | '#d8d8d8';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Netflix Sans';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '500' | '600';

export type SpacingToken = '1px' | '10px' | '12px' | '20px' | '22px' | '24px' | '27px' | '30px' | '32px' | '34px' | '64px' | '96px' | '100px' | '128px' | '148px' | '314px';

export type RadiusToken = '2px' | '8px' | '16px' | '20px' | '50px';

export type DurationToken = '100ms' | '200ms' | '300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
