// Generated by designlang v7.0.0
// Source: https://raycast.com
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFFFF6363)
    val ActionSecondary = Color(0xFF8CD6FF)
    val SurfaceDefault = Color(0xFF07080A)
    val TextBody = Color(0xFFFFFFFF)
    val BrandPrimary = Color(0xFFFF6363)
    val BrandSecondary = Color(0xFF8CD6FF)
    val NeutralN100 = Color(0xFFFFFFFF)
    val NeutralN200 = Color(0xFF6A6B6C)
    val NeutralN300 = Color(0xFF9C9C9D)
    val NeutralN400 = Color(0xFF434345)
    val NeutralN500 = Color(0xFFE6E6E6)
    val NeutralN600 = Color(0xFF2F3031)
    val NeutralN700 = Color(0xFF1B1C1E)
    val NeutralN800 = Color(0xFF8E8C90)
    val NeutralN900 = Color(0xFF111214)
    val BackgroundBg0 = Color(0xFF07080A)
    val BackgroundBg1 = Color(0xFF000000)
    val BackgroundBg2 = Color(0xFFFFFFFF)
    val BackgroundBg3 = Color(0xFF9EBED7)
    val BackgroundBg4 = Color(0xFF111214)
    val BackgroundBg5 = Color(0xFFD72A2A)
    val TextText0 = Color(0xFFFFFFFF)
    val TextText1 = Color(0xFF9C9C9D)
    val TextText2 = Color(0xFF2F3031)
    val TextText3 = Color(0xFF6A6B6C)
    val TextText4 = Color(0xFFE6E6E6)
    val TextText5 = Color(0xFFFF6363)
    val TextText6 = Color(0xFF434345)
    val TextText7 = Color(0xFF8CD6FF)
    val TextText8 = Color(0xFF000000)
    val SpacingS0 = 1.dp
    val SpacingS1 = 45.dp
    val SpacingS2 = 56.dp
    val SpacingS3 = 64.dp
    val SpacingS4 = 72.dp
    val SpacingS5 = 80.dp
    val SpacingS6 = 96.dp
    val SpacingS7 = 102.dp
    val SpacingS8 = 120.dp
    val SpacingS9 = 128.dp
    val SpacingS10 = 137.dp
    val SpacingS11 = 148.dp
    val SpacingS12 = 169.dp
    val SpacingS13 = 200.dp
    val SpacingS14 = 212.dp
    val SpacingS15 = 217.dp
    val SpacingS16 = 224.dp
    val SpacingS17 = 325.dp
    val SpacingS18 = 370.dp
    val SpacingS19 = 400.dp
    val SpacingS20 = 409.dp
    val SpacingS21 = 416.dp
    val RadiusR0 = 2.dp
    val RadiusR1 = 5.dp
    val RadiusR2 = 8.dp
    val RadiusR3 = 11.dp
    val RadiusR4 = 16.dp
    val RadiusR5 = 19.dp
    val RadiusR6 = 22.dp
    val RadiusR7 = 31.dp
    val RadiusR8 = 36.dp
    val RadiusR9 = 43.dp
    val RadiusR10 = 86.dp
    val RadiusR11 = 100.dp
    val RadiusR12 = 1000.dp
    val RadiusR13 = 99999.dp
}
